// Canonical fallback catalog consumed by the modern core and the legacy Sport UI.
export const CATALOG = [
    { key: "strength", fr: "Musculation", en: "Strength training", met: 5.0, mode: "reps", equipment: "bodyweight" },
    { key: "bodyweight_strength", fr: "Musculation poids du corps", en: "Bodyweight strength", met: 5.2, mode: "reps", equipment: "bodyweight" },
    { key: "resistance_band_strength", fr: "Renforcement elastique", en: "Resistance band strength", met: 4.8, mode: "reps", equipment: "band" },
    { key: "core_abs", fr: "Abdos / core", en: "Abs / core", met: 4.5, mode: "reps", equipment: "bodyweight" },
    { key: "plank_core", fr: "Gainage / core", en: "Core / plank", met: 4.2, mode: "time", equipment: "bodyweight" },
    { key: "running", fr: "Course a pied", en: "Running", met: 8.3, mode: "time", equipment: "outdoor" },
    { key: "cycling", fr: "Velo", en: "Cycling", met: 6.8, mode: "time", equipment: "outdoor" },
    { key: "swimming", fr: "Natation", en: "Swimming", met: 6.0, mode: "time", equipment: "pool" },
    { key: "climbing", fr: "Escalade", en: "Climbing", met: 8.0, mode: "time", equipment: "wall" },
    { key: "walking", fr: "Marche rapide", en: "Brisk walk", met: 3.8, mode: "time", equipment: "outdoor" },
    { key: "hiking", fr: "Randonnee", en: "Hiking", met: 6.0, mode: "time", equipment: "outdoor" },
    { key: "rowing", fr: "Rameur", en: "Rowing", met: 7.0, mode: "time", equipment: "machine" },
    { key: "jump_rope", fr: "Corde a sauter", en: "Jump rope", met: 12.0, mode: "time", equipment: "rope" },
    { key: "basketball", fr: "Basket", en: "Basketball", met: 6.5, mode: "time", equipment: "outdoor" },
    { key: "table_tennis", fr: "Ping-pong", en: "Table tennis", met: 4.0, mode: "time", equipment: "mixed" },
    { key: "boxing", fr: "Boxe", en: "Boxing", met: 12.8, mode: "time", equipment: "boxing" },
    { key: "hiit", fr: "HIIT", en: "HIIT", met: 7.8, mode: "time", equipment: "mixed" },
    { key: "yoga", fr: "Yoga", en: "Yoga", met: 2.5, mode: "time", equipment: "mat" },
    { key: "mobility", fr: "Mobilite", en: "Mobility", met: 2.0, mode: "time", equipment: "mat" },
  ];
export const EQUIPMENT = [
    ["bodyweight", "Poids du corps", "Bodyweight"],
    ["machine", "Machine", "Machine"],
    ["dumbbell", "Halteres", "Dumbbells"],
    ["barbell", "Barre", "Barbell"],
    ["plate", "Disque / plate", "Plate"],
    ["band", "Elastique", "Resistance band"],
    ["kettlebell", "Kettlebell", "Kettlebell"],
    ["rope", "Corde a sauter", "Jump rope"],
    ["boxing", "Boxe", "Boxing"],
    ["outdoor", "Exterieur", "Outdoor"],
    ["pool", "Piscine", "Pool"],
    ["wall", "Mur / voie", "Wall / route"],
    ["mat", "Tapis", "Mat"],
    ["mixed", "Mixte", "Mixed"],
  ];

export const GOALS = [
    ["strength", "Force", "Strength"],
    ["cardio", "Cardio", "Cardio"],
    ["boxing", "Boxe", "Boxing"],
    ["basketball", "Basket", "Basketball"],
    ["mobility", "Mobilite", "Mobility"],
    ["climb", "Escalade", "Climbing"],
    ["swim", "Natation", "Swimming"],
    ["free", "Libre", "Free"],
  ];
export const LEVELS = [
    ["beginner", "Debutant", "Beginner"],
    ["regular", "Intermediaire", "Regular"],
    ["advanced", "Avance", "Advanced"],
  ];
export const SPORT_FAMILIES = [
    ["all", "Toutes familles", "All families"],
    ["push", "Push", "Push"],
    ["pull", "Pull", "Pull"],
    ["legs", "Jambes", "Legs"],
    ["core", "Core", "Core"],
    ["cardio", "Cardio", "Cardio"],
    ["boxing", "Boxe", "Boxing"],
    ["mobility", "Mobilite", "Mobility"],
  ];

export const PROGRAM_LOADS = [
    ["Squat arriere", 60],
    ["Souleve de terre", 100],
    ["Souleve de terre roumain", 80],
    ["Front squat", 45],
    ["Front squat ou Goblet squat", 45],
    ["Fentes bulgares", 32, "2 x 16 kg"],
    ["Developpe couche", 50],
    ["Developpe couche prise serree", 45],
    ["Developpe incline barre", 45],
    ["Developpe incline halteres", 40, "2 x 20 kg"],
    ["Developpe halteres plat", 40, "2 x 20 kg"],
    ["Developpe halteres ou pompes lestees", 40, "2 x 20 kg"],
    ["Tractions pronation", 0, "Poids du corps"],
    ["Tractions supination", 0, "Poids du corps"],
    ["Tractions lestees ou poids du corps", 0, "Poids du corps"],
    ["Rowing barre", 60],
    ["Rowing haltere un bras", 30],
    ["Developpe militaire barre", 35],
    ["Developpe militaire halteres", 32, "2 x 16 kg"],
    ["Elevations laterales", 8],
    ["Oiseau halteres", 6],
    ["Curl halteres", 14],
    ["Curl marteau", 17.5],
    ["Curl barre", 30],
    ["Extension triceps haltere au-dessus de la tete", 20],
    ["Extension triceps", 20],
  ];

export const EXERCISE_LIBRARY = [
    { key: "pushup", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Push-up", en: "Push-up", mode: "reps", reps: 15, sets: 3, rest: 60 },
    { key: "squat", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Squat", en: "Squat", mode: "reps", reps: 20, sets: 3, rest: 60 },
    { key: "lunge", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Fentes", en: "Lunges", mode: "reps", reps: 12, sets: 3, rest: 60 },
    { key: "plank", goal: "strength", equipment: "bodyweight", activityKey: "plank_core", fr: "Gainage", en: "Plank", mode: "time", seconds: 45, sets: 3, rest: 60 },
    { key: "incline_pushup", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Push-up incline", en: "Incline push-up", mode: "reps", reps: 12, sets: 3, rest: 60 },
    { key: "diamond_pushup", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Push-up serre", en: "Diamond push-up", mode: "reps", reps: 8, sets: 3, rest: 75 },
    { key: "glute_bridge", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Pont fessier", en: "Glute bridge", mode: "reps", reps: 15, sets: 3, rest: 45 },
    { key: "calf_raise", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Mollets debout", en: "Standing calf raise", mode: "reps", reps: 20, sets: 3, rest: 45 },
    { key: "side_plank", goal: "strength", equipment: "bodyweight", activityKey: "plank_core", fr: "Gainage lateral", en: "Side plank", mode: "time", seconds: 35, sets: 3, rest: 45 },
    { key: "dead_bug", goal: "strength", equipment: "bodyweight", activityKey: "plank_core", fr: "Dead bug", en: "Dead bug", mode: "reps", reps: 10, sets: 3, rest: 45 },
    { key: "pike_pushup", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Pike push-up", en: "Pike push-up", mode: "reps", reps: 8, sets: 3, rest: 75 },
    { key: "chair_dip", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Dips sur chaise", en: "Chair dips", mode: "reps", reps: 10, sets: 3, rest: 60 },
    { key: "single_leg_glute_bridge", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Pont fessier une jambe", en: "Single-leg glute bridge", mode: "reps", reps: 10, sets: 3, rest: 60 },
    { key: "wall_sit", goal: "strength", equipment: "bodyweight", activityKey: "plank_core", fr: "Chaise murale", en: "Wall sit", mode: "time", seconds: 45, sets: 3, rest: 60 },
    { key: "reverse_lunge", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Fente arriere", en: "Reverse lunge", mode: "reps", reps: 10, sets: 3, rest: 60 },
    { key: "step_up", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Step-up", en: "Step-up", mode: "reps", reps: 10, sets: 3, rest: 60 },
    { key: "hollow_hold", goal: "strength", equipment: "bodyweight", activityKey: "plank_core", fr: "Hollow hold", en: "Hollow hold", mode: "time", seconds: 30, sets: 3, rest: 45 },
    { key: "crunch", goal: "strength", equipment: "bodyweight", activityKey: "core_abs", fr: "Crunch", en: "Crunch", mode: "reps", reps: 20, sets: 3, rest: 45 },
    { key: "reverse_crunch", goal: "strength", equipment: "bodyweight", activityKey: "core_abs", fr: "Crunch inverse", en: "Reverse crunch", mode: "reps", reps: 15, sets: 3, rest: 45 },
    { key: "bicycle_crunch", goal: "strength", equipment: "bodyweight", activityKey: "core_abs", fr: "Crunch bicyclette", en: "Bicycle crunch", mode: "reps", reps: 20, sets: 3, rest: 45 },
    { key: "sit_up", goal: "strength", equipment: "bodyweight", activityKey: "core_abs", fr: "Sit-up", en: "Sit-up", mode: "reps", reps: 15, sets: 3, rest: 60 },
    { key: "lying_leg_raise", goal: "strength", equipment: "bodyweight", activityKey: "core_abs", fr: "Elevation jambes au sol", en: "Lying leg raise", mode: "reps", reps: 12, sets: 3, rest: 60 },
    { key: "hanging_knee_raise", goal: "strength", equipment: "bodyweight", activityKey: "core_abs", fr: "Elevation genoux sous barre", en: "Hanging knee raise", mode: "reps", reps: 10, sets: 3, rest: 75 },
    { key: "hanging_leg_raise", goal: "strength", equipment: "bodyweight", activityKey: "core_abs", fr: "Elevation jambes sous barre", en: "Hanging leg raise", mode: "reps", reps: 8, sets: 3, rest: 90 },
    { key: "toes_to_bar", goal: "strength", equipment: "bodyweight", activityKey: "core_abs", fr: "Pieds a la barre", en: "Toes to bar", mode: "reps", reps: 6, sets: 3, rest: 90 },
    { key: "flutter_kicks", goal: "strength", equipment: "bodyweight", activityKey: "core_abs", fr: "Battements de jambes", en: "Flutter kicks", mode: "time", seconds: 35, sets: 3, rest: 45 },
    { key: "v_up", goal: "strength", equipment: "bodyweight", activityKey: "core_abs", fr: "V-up", en: "V-up", mode: "reps", reps: 10, sets: 3, rest: 60 },
    { key: "russian_twist", goal: "strength", equipment: "bodyweight", activityKey: "core_abs", fr: "Russian twist", en: "Russian twist", mode: "reps", reps: 20, sets: 3, rest: 45 },
    { key: "mountain_climber", goal: "cardio", equipment: "bodyweight", activityKey: "hiit", fr: "Mountain climbers", en: "Mountain climbers", mode: "time", seconds: 40, sets: 6, rest: 20 },
    { key: "burpee", goal: "cardio", equipment: "bodyweight", activityKey: "hiit", fr: "Burpees", en: "Burpees", mode: "reps", reps: 8, sets: 5, rest: 45 },
    { key: "jumping_jack", goal: "cardio", equipment: "bodyweight", activityKey: "hiit", fr: "Jumping jacks", en: "Jumping jacks", mode: "time", seconds: 45, sets: 5, rest: 20 },
    { key: "jump_rope", goal: "cardio", equipment: "rope", activityKey: "jump_rope", fr: "Corde a sauter", en: "Jump rope", mode: "time", seconds: 60, sets: 10, rest: 30 },
    { key: "jump_rope_easy", goal: "cardio", equipment: "rope", activityKey: "jump_rope", fr: "Corde a sauter facile", en: "Easy jump rope", mode: "time", seconds: 45, sets: 8, rest: 45 },
    { key: "table_tennis", goal: "cardio", equipment: "mixed", activityKey: "table_tennis", fr: "Ping-pong", en: "Table tennis", mode: "time", seconds: 600, sets: 1, rest: 0 },
    { key: "band_row", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Tirage elastique", en: "Band row", mode: "reps", reps: 15, sets: 3, rest: 60 },
    { key: "band_curl", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Curl elastique", en: "Band curl", mode: "reps", reps: 15, sets: 3, rest: 45 },
    { key: "band_triceps", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Extension triceps elastique", en: "Band triceps extension", mode: "reps", reps: 15, sets: 3, rest: 45 },
    { key: "band_press", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Presse elastique", en: "Band chest press", mode: "reps", reps: 12, sets: 3, rest: 60 },
    { key: "band_face_pull", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Face pull elastique", en: "Band face pull", mode: "reps", reps: 15, sets: 3, rest: 45 },
    { key: "band_lateral_walk", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Marche laterale elastique", en: "Band lateral walk", mode: "reps", reps: 12, sets: 3, rest: 45 },
    { key: "band_pull_apart", goal: "mobility", equipment: "band", activityKey: "mobility", fr: "Ouverture epaules elastique", en: "Band pull-apart", mode: "reps", reps: 15, sets: 2, rest: 30 },
    { key: "band_squat", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Squat elastique", en: "Band squat", mode: "reps", reps: 15, sets: 3, rest: 60 },
    { key: "band_deadlift", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Souleve de terre elastique", en: "Band deadlift", mode: "reps", reps: 12, sets: 3, rest: 75 },
    { key: "band_overhead_press", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Developpe epaules elastique", en: "Band overhead press", mode: "reps", reps: 12, sets: 3, rest: 60 },
    { key: "band_lat_pulldown", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Tirage vertical elastique", en: "Band lat pulldown", mode: "reps", reps: 15, sets: 3, rest: 60 },
    { key: "band_hamstring_curl", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Leg curl elastique", en: "Band hamstring curl", mode: "reps", reps: 12, sets: 3, rest: 45 },
    { key: "band_glute_kickback", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Kickback fessier elastique", en: "Band glute kickback", mode: "reps", reps: 12, sets: 3, rest: 45 },
    { key: "band_assisted_pullup", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Traction assistee elastique", en: "Band-assisted pull-up", mode: "reps", reps: 6, sets: 4, rest: 90, metValue: 5.8 },
    { key: "band_good_morning", goal: "strength", equipment: "band", activityKey: "resistance_band_strength", fr: "Good morning elastique", en: "Band good morning", mode: "reps", reps: 15, sets: 3, rest: 60, metValue: 4.8 },
    { key: "band_pallof_press", goal: "strength", equipment: "band", activityKey: "core_abs", fr: "Pallof press elastique", en: "Band Pallof press", mode: "reps", reps: 10, sets: 3, rest: 45, metValue: 4.4 },
    { key: "band_external_rotation", goal: "mobility", equipment: "band", activityKey: "mobility", fr: "Rotation externe elastique", en: "Band external rotation", mode: "reps", reps: 12, sets: 2, rest: 25 },
    { key: "band_dislocates", goal: "mobility", equipment: "band", activityKey: "mobility", fr: "Passage epaules elastique", en: "Band shoulder pass-through", mode: "reps", reps: 10, sets: 2, rest: 25 },
    { key: "dumbbell_press", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Developpe halteres", en: "Dumbbell press", mode: "reps", reps: 10, sets: 3, rest: 75 },
    { key: "dumbbell_row", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Rowing haltere", en: "Dumbbell row", mode: "reps", reps: 10, sets: 3, rest: 75 },
    { key: "dumbbell_goblet_squat", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Goblet squat haltere", en: "Dumbbell goblet squat", mode: "reps", reps: 10, sets: 3, rest: 75 },
    { key: "dumbbell_rdl", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Souleve de terre roumain halteres", en: "Dumbbell Romanian deadlift", mode: "reps", reps: 10, sets: 3, rest: 90 },
    { key: "dumbbell_shoulder_press", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Developpe epaules halteres", en: "Dumbbell shoulder press", mode: "reps", reps: 10, sets: 3, rest: 75 },
    { key: "dumbbell_carry", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Farmer carry halteres", en: "Dumbbell farmer carry", mode: "time", seconds: 40, sets: 4, rest: 60 },
    { key: "dumbbell_lunge", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Fentes halteres", en: "Dumbbell lunges", mode: "reps", reps: 10, sets: 3, rest: 75 },
    { key: "dumbbell_step_up", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Step-up halteres", en: "Dumbbell step-up", mode: "reps", reps: 10, sets: 3, rest: 75 },
    { key: "dumbbell_floor_press", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Developpe au sol halteres", en: "Dumbbell floor press", mode: "reps", reps: 10, sets: 3, rest: 75 },
    { key: "dumbbell_fly", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Ecarte halteres", en: "Dumbbell fly", mode: "reps", reps: 10, sets: 3, rest: 75 },
    { key: "dumbbell_lateral_raise", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Elevation laterale halteres", en: "Dumbbell lateral raise", mode: "reps", reps: 12, sets: 3, rest: 60 },
    { key: "dumbbell_biceps_curl", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Curl biceps halteres", en: "Dumbbell biceps curl", mode: "reps", reps: 12, sets: 3, rest: 60 },
    { key: "dumbbell_triceps_extension", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Extension triceps haltere", en: "Dumbbell triceps extension", mode: "reps", reps: 12, sets: 3, rest: 60 },
    { key: "dumbbell_renegade_row", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Renegade row", en: "Renegade row", mode: "reps", reps: 8, sets: 3, rest: 90 },
    { key: "dumbbell_thruster", goal: "cardio", equipment: "dumbbell", activityKey: "hiit", fr: "Thruster halteres", en: "Dumbbell thruster", mode: "reps", reps: 10, sets: 4, rest: 60 },
    { key: "dumbbell_bench_press", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Developpe couche halteres", en: "Dumbbell bench press", mode: "reps", reps: 10, sets: 3, rest: 90, metValue: 5.8 },
    { key: "dumbbell_chest_supported_row", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Rowing halteres banc incline", en: "Chest-supported dumbbell row", mode: "reps", reps: 10, sets: 3, rest: 75, metValue: 5.4 },
    { key: "dumbbell_bulgarian_split_squat", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Bulgarian split squat halteres", en: "Dumbbell Bulgarian split squat", mode: "reps", reps: 8, sets: 3, rest: 90, metValue: 6.5 },
    { key: "dumbbell_single_arm_snatch", goal: "cardio", equipment: "dumbbell", activityKey: "hiit", fr: "Snatch haltere un bras", en: "Single-arm dumbbell snatch", mode: "reps", reps: 8, sets: 5, rest: 60, metValue: 8.5 },
    { key: "dumbbell_hammer_curl", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Curl marteau halteres", en: "Dumbbell hammer curl", mode: "reps", reps: 12, sets: 3, rest: 60, metValue: 4.8 },
    { key: "dumbbell_skull_crusher", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Barre au front halteres", en: "Dumbbell skull crusher", mode: "reps", reps: 10, sets: 3, rest: 60, metValue: 4.8 },
    { key: "dumbbell_incline_press", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Developpe incline halteres", en: "Incline dumbbell press", mode: "reps", reps: 10, sets: 3, rest: 90, metValue: 5.8 },
    { key: "dumbbell_pullover", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Pull-over haltere", en: "Dumbbell pullover", mode: "reps", reps: 10, sets: 3, rest: 75, metValue: 5.2 },
    { key: "dumbbell_reverse_fly", goal: "strength", equipment: "dumbbell", activityKey: "strength", fr: "Oiseau halteres", en: "Dumbbell reverse fly", mode: "reps", reps: 12, sets: 3, rest: 60, metValue: 4.8 },
    { key: "barbell_squat", goal: "strength", equipment: "barbell", activityKey: "strength", fr: "Squat barre", en: "Barbell squat", mode: "reps", reps: 6, sets: 4, rest: 120 },
    { key: "barbell_deadlift", goal: "strength", equipment: "barbell", activityKey: "strength", fr: "Souleve de terre barre", en: "Barbell deadlift", mode: "reps", reps: 5, sets: 4, rest: 150 },
    { key: "barbell_bench", goal: "strength", equipment: "barbell", activityKey: "strength", fr: "Developpe couche barre", en: "Barbell bench press", mode: "reps", reps: 6, sets: 4, rest: 120 },
    { key: "barbell_row", goal: "strength", equipment: "barbell", activityKey: "strength", fr: "Rowing barre", en: "Barbell row", mode: "reps", reps: 8, sets: 4, rest: 90 },
    { key: "barbell_front_squat", goal: "strength", equipment: "barbell", activityKey: "strength", fr: "Front squat barre", en: "Barbell front squat", mode: "reps", reps: 6, sets: 4, rest: 120, metValue: 6.5 },
    { key: "barbell_overhead_press", goal: "strength", equipment: "barbell", activityKey: "strength", fr: "Developpe militaire barre", en: "Barbell overhead press", mode: "reps", reps: 6, sets: 4, rest: 120, metValue: 5.6 },
    { key: "barbell_hip_thrust", goal: "strength", equipment: "barbell", activityKey: "strength", fr: "Hip thrust barre", en: "Barbell hip thrust", mode: "reps", reps: 10, sets: 4, rest: 90, metValue: 5.6 },
    { key: "barbell_power_clean", goal: "cardio", equipment: "barbell", activityKey: "hiit", fr: "Power clean barre", en: "Barbell power clean", mode: "reps", reps: 5, sets: 5, rest: 120, metValue: 8.0 },
    { key: "barbell_incline_bench", goal: "strength", equipment: "barbell", activityKey: "strength", fr: "Developpe incline barre", en: "Barbell incline bench press", mode: "reps", reps: 8, sets: 4, rest: 105, metValue: 6.1 },
    { key: "barbell_lunge", goal: "strength", equipment: "barbell", activityKey: "strength", fr: "Fentes barre", en: "Barbell lunge", mode: "reps", reps: 8, sets: 3, rest: 90, metValue: 6.2 },
    { key: "barbell_curl", goal: "strength", equipment: "barbell", activityKey: "strength", fr: "Curl barre", en: "Barbell curl", mode: "reps", reps: 10, sets: 3, rest: 60, metValue: 4.8 },
    { key: "barbell_good_morning", goal: "strength", equipment: "barbell", activityKey: "strength", fr: "Good morning barre", en: "Barbell good morning", mode: "reps", reps: 8, sets: 3, rest: 90, metValue: 5.5 },
    { key: "barbell_close_grip_bench", goal: "strength", equipment: "barbell", activityKey: "strength", fr: "Developpe serre barre", en: "Close-grip barbell bench", mode: "reps", reps: 8, sets: 4, rest: 105, metValue: 5.8 },
    { key: "barbell_pendlay_row", goal: "strength", equipment: "barbell", activityKey: "strength", fr: "Rowing Pendlay", en: "Pendlay row", mode: "reps", reps: 6, sets: 4, rest: 105, metValue: 5.8 },
    { key: "plate_floor_press", goal: "strength", equipment: "plate", activityKey: "strength", fr: "Developpe plate au sol", en: "Plate floor press", mode: "reps", reps: 12, sets: 3, rest: 75, metValue: 5.4 },
    { key: "plate_squeeze_press", goal: "strength", equipment: "plate", activityKey: "strength", fr: "Squeeze press plate", en: "Plate squeeze press", mode: "reps", reps: 12, sets: 3, rest: 60, metValue: 5.2 },
    { key: "plate_overhead_press", goal: "strength", equipment: "plate", activityKey: "strength", fr: "Developpe epaules plate", en: "Plate overhead press", mode: "reps", reps: 10, sets: 3, rest: 75, metValue: 5.2 },
    { key: "plate_front_raise", goal: "strength", equipment: "plate", activityKey: "strength", fr: "Elevation frontale plate", en: "Plate front raise", mode: "reps", reps: 12, sets: 3, rest: 45, metValue: 4.6 },
    { key: "plate_russian_twist", goal: "strength", equipment: "plate", activityKey: "core_abs", fr: "Russian twist plate", en: "Plate Russian twist", mode: "reps", reps: 20, sets: 3, rest: 45, metValue: 5.0 },
    { key: "plate_around_world", goal: "mobility", equipment: "plate", activityKey: "mobility", fr: "Tour du monde plate", en: "Plate around the world", mode: "reps", reps: 8, sets: 3, rest: 45, metValue: 4.8 },
    { key: "plate_halo", goal: "mobility", equipment: "plate", activityKey: "mobility", fr: "Halo plate", en: "Plate halo", mode: "reps", reps: 10, sets: 3, rest: 45, metValue: 4.4 },
    { key: "plate_squat", goal: "strength", equipment: "plate", activityKey: "strength", fr: "Squat plate", en: "Plate squat", mode: "reps", reps: 12, sets: 3, rest: 75, metValue: 5.8 },
    { key: "plate_lunge", goal: "strength", equipment: "plate", activityKey: "strength", fr: "Fentes plate", en: "Plate lunge", mode: "reps", reps: 10, sets: 3, rest: 75, metValue: 5.8 },
    { key: "kettlebell_swing", goal: "strength", equipment: "kettlebell", activityKey: "hiit", fr: "Swing kettlebell", en: "Kettlebell swing", mode: "reps", reps: 15, sets: 4, rest: 60 },
    { key: "kettlebell_goblet", goal: "strength", equipment: "kettlebell", activityKey: "strength", fr: "Goblet squat kettlebell", en: "Kettlebell goblet squat", mode: "reps", reps: 12, sets: 3, rest: 75 },
    { key: "kettlebell_clean_press", goal: "strength", equipment: "kettlebell", activityKey: "strength", fr: "Clean press kettlebell", en: "Kettlebell clean and press", mode: "reps", reps: 6, sets: 3, rest: 90 },
    { key: "machine_press", goal: "strength", equipment: "machine", activityKey: "strength", fr: "Presse machine", en: "Machine press", mode: "reps", reps: 10, sets: 3, rest: 90 },
    { key: "machine_leg_press", goal: "strength", equipment: "machine", activityKey: "strength", fr: "Presse a cuisses", en: "Leg press", mode: "reps", reps: 10, sets: 3, rest: 90 },
    { key: "machine_lat_pulldown", goal: "strength", equipment: "machine", activityKey: "strength", fr: "Tirage vertical", en: "Lat pulldown", mode: "reps", reps: 10, sets: 3, rest: 75 },
    { key: "machine_seated_row", goal: "strength", equipment: "machine", activityKey: "strength", fr: "Rowing assis machine", en: "Seated cable row", mode: "reps", reps: 10, sets: 3, rest: 75 },
    { key: "machine_leg_curl", goal: "strength", equipment: "machine", activityKey: "strength", fr: "Leg curl", en: "Leg curl", mode: "reps", reps: 12, sets: 3, rest: 60 },
    { key: "machine_cable_triceps", goal: "strength", equipment: "machine", activityKey: "strength", fr: "Triceps poulie", en: "Cable triceps pushdown", mode: "reps", reps: 12, sets: 3, rest: 60 },
    { key: "cable_face_pull", goal: "strength", equipment: "machine", activityKey: "strength", fr: "Face pull poulie", en: "Cable face pull", mode: "reps", reps: 15, sets: 3, rest: 45, metValue: 4.6 },
    { key: "machine_pec_deck", goal: "strength", equipment: "machine", activityKey: "strength", fr: "Pec deck", en: "Pec deck", mode: "reps", reps: 12, sets: 3, rest: 60, metValue: 4.8 },
    { key: "cable_low_row", goal: "strength", equipment: "machine", activityKey: "strength", fr: "Rowing poulie basse", en: "Cable low row", mode: "reps", reps: 10, sets: 3, rest: 75, metValue: 5.0 },
    { key: "easy_run", goal: "cardio", equipment: "outdoor", activityKey: "running", fr: "Course facile", en: "Easy run", mode: "time", seconds: 1200, sets: 1, rest: 0, distanceM: 3000 },
    { key: "run_intervals", goal: "cardio", equipment: "outdoor", activityKey: "running", fr: "Intervalles course", en: "Run intervals", mode: "time", seconds: 60, sets: 8, rest: 60 },
    { key: "tempo_run", goal: "cardio", equipment: "outdoor", activityKey: "running", fr: "Course tempo", en: "Tempo run", mode: "time", seconds: 900, sets: 1, rest: 0, distanceM: 2500 },
    { key: "hill_repeats", goal: "cardio", equipment: "outdoor", activityKey: "running", fr: "Cotes repetees", en: "Hill repeats", mode: "time", seconds: 45, sets: 8, rest: 90 },
    { key: "brisk_walk", goal: "cardio", equipment: "outdoor", activityKey: "walking", fr: "Marche rapide", en: "Brisk walk", mode: "time", seconds: 1800, sets: 1, rest: 0, distanceM: 2500 },
    { key: "hike_block", goal: "cardio", equipment: "outdoor", activityKey: "hiking", fr: "Bloc randonnee", en: "Hiking block", mode: "time", seconds: 3600, sets: 1, rest: 0, distanceM: 5000 },
    { key: "cycling_easy", goal: "cardio", equipment: "outdoor", activityKey: "cycling", fr: "Velo facile", en: "Easy cycling", mode: "time", seconds: 1800, sets: 1, rest: 0 },
    { key: "cycling_intervals", goal: "cardio", equipment: "outdoor", activityKey: "cycling", fr: "Intervalles velo", en: "Cycling intervals", mode: "time", seconds: 120, sets: 6, rest: 90 },
    { key: "rowing", goal: "cardio", equipment: "machine", activityKey: "rowing", fr: "Rameur", en: "Rowing", mode: "time", seconds: 300, sets: 4, rest: 90 },
    { key: "rowing_easy", goal: "cardio", equipment: "machine", activityKey: "rowing", fr: "Rameur facile", en: "Easy rowing", mode: "time", seconds: 900, sets: 1, rest: 0 },
    { key: "basketball_1h", goal: "basketball", equipment: "outdoor", activityKey: "basketball", fr: "Basket", en: "Basketball", mode: "time", seconds: 3600, sets: 1, rest: 0 },
    { key: "basketball_shootaround", goal: "basketball", equipment: "outdoor", activityKey: "basketball", fr: "Shoot basket", en: "Basketball shootaround", mode: "time", seconds: 1800, sets: 1, rest: 0 },
    { key: "hiit_bodyweight", goal: "cardio", equipment: "bodyweight", activityKey: "hiit", fr: "HIIT poids du corps", en: "Bodyweight HIIT", mode: "time", seconds: 40, sets: 8, rest: 20 },
    { key: "hips", goal: "mobility", equipment: "mat", activityKey: "mobility", fr: "Mobilite hanches", en: "Hip mobility", mode: "time", seconds: 60, sets: 3, rest: 20 },
    { key: "shoulders", goal: "mobility", equipment: "mat", activityKey: "mobility", fr: "Mobilite epaules", en: "Shoulder mobility", mode: "time", seconds: 60, sets: 3, rest: 20 },
    { key: "breathing", goal: "mobility", equipment: "mat", activityKey: "yoga", fr: "Respiration / relachement", en: "Breathing / release", mode: "time", seconds: 180, sets: 1, rest: 0 },
    { key: "cat_cow", goal: "mobility", equipment: "mat", activityKey: "mobility", fr: "Dos rond dos creux", en: "Cat-cow", mode: "time", seconds: 45, sets: 2, rest: 15 },
    { key: "thoracic_rotation", goal: "mobility", equipment: "mat", activityKey: "mobility", fr: "Rotation thoracique", en: "Thoracic rotation", mode: "reps", reps: 8, sets: 2, rest: 20 },
    { key: "ankle_mobility", goal: "mobility", equipment: "mat", activityKey: "mobility", fr: "Mobilite chevilles", en: "Ankle mobility", mode: "time", seconds: 45, sets: 2, rest: 20 },
    { key: "hamstring_flow", goal: "mobility", equipment: "mat", activityKey: "yoga", fr: "Flow ischios", en: "Hamstring flow", mode: "time", seconds: 90, sets: 2, rest: 20 },
    { key: "world_greatest_stretch", goal: "mobility", equipment: "mat", activityKey: "mobility", fr: "World greatest stretch", en: "World's greatest stretch", mode: "time", seconds: 60, sets: 2, rest: 20 },
    { key: "couch_stretch", goal: "mobility", equipment: "mat", activityKey: "mobility", fr: "Etirement psoas", en: "Couch stretch", mode: "time", seconds: 60, sets: 2, rest: 20 },
    { key: "pigeon_stretch", goal: "mobility", equipment: "mat", activityKey: "yoga", fr: "Pigeon fessier", en: "Pigeon stretch", mode: "time", seconds: 60, sets: 2, rest: 20 },
    { key: "deep_squat_hold", goal: "mobility", equipment: "bodyweight", activityKey: "mobility", fr: "Squat profond tenu", en: "Deep squat hold", mode: "time", seconds: 60, sets: 2, rest: 30 },
    { key: "wrist_mobility", goal: "mobility", equipment: "mat", activityKey: "mobility", fr: "Mobilite poignets", en: "Wrist mobility", mode: "time", seconds: 45, sets: 2, rest: 15 },
    { key: "neck_mobility", goal: "mobility", equipment: "mat", activityKey: "mobility", fr: "Mobilite nuque", en: "Neck mobility", mode: "time", seconds: 45, sets: 2, rest: 15 },
    { key: "scapular_wall_slide", goal: "mobility", equipment: "bodyweight", activityKey: "mobility", fr: "Wall slide scapulaire", en: "Scapular wall slide", mode: "reps", reps: 10, sets: 2, rest: 25 },
    { key: "calf_stretch_flow", goal: "mobility", equipment: "mat", activityKey: "mobility", fr: "Flow mollets chevilles", en: "Calf and ankle flow", mode: "time", seconds: 60, sets: 2, rest: 20 },
    { key: "climb_easy", goal: "climb", equipment: "wall", activityKey: "climbing", fr: "Voies faciles", en: "Easy routes", mode: "time", seconds: 240, sets: 4, rest: 120 },
    { key: "climb_project", goal: "climb", equipment: "wall", activityKey: "climbing", fr: "Projet / essais", en: "Project attempts", mode: "time", seconds: 180, sets: 6, rest: 180 },
    { key: "finger_warmup", goal: "climb", equipment: "bodyweight", activityKey: "mobility", fr: "Echauffement doigts/epaules", en: "Finger/shoulder warm-up", mode: "time", seconds: 420, sets: 1, rest: 0 },
    { key: "climb_technique_feet", goal: "climb", equipment: "wall", activityKey: "climbing", fr: "Technique pieds", en: "Footwork technique", mode: "time", seconds: 180, sets: 4, rest: 90 },
    { key: "climb_endurance", goal: "climb", equipment: "wall", activityKey: "climbing", fr: "Volume endurance", en: "Endurance volume", mode: "time", seconds: 600, sets: 3, rest: 180 },
    { key: "climb_downclimb", goal: "climb", equipment: "wall", activityKey: "climbing", fr: "Montee descente controlee", en: "Controlled up/down climb", mode: "time", seconds: 240, sets: 3, rest: 120 },
    { key: "scap_pull", goal: "climb", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Tractions scapulaires", en: "Scapular pulls", mode: "reps", reps: 8, sets: 3, rest: 60 },
    { key: "swim_warmup", goal: "swim", equipment: "pool", activityKey: "swimming", fr: "Echauffement nage", en: "Swim warm-up", mode: "time", seconds: 300, sets: 1, rest: 60, distanceM: 200 },
    { key: "swim_intervals", goal: "swim", equipment: "pool", activityKey: "swimming", fr: "Series nage", en: "Swim intervals", mode: "time", seconds: 120, sets: 6, rest: 45, distanceM: 50 },
    { key: "swim_cooldown", goal: "swim", equipment: "pool", activityKey: "swimming", fr: "Retour calme nage", en: "Swim cool down", mode: "time", seconds: 240, sets: 1, rest: 0, distanceM: 100 },
    { key: "swim_drill_kick", goal: "swim", equipment: "pool", activityKey: "swimming", fr: "Battements jambes", en: "Kick drill", mode: "time", seconds: 90, sets: 6, rest: 30, distanceM: 50 },
    { key: "swim_pull", goal: "swim", equipment: "pool", activityKey: "swimming", fr: "Pull nage", en: "Pull swim", mode: "time", seconds: 120, sets: 5, rest: 45, distanceM: 50 },
    { key: "swim_endurance", goal: "swim", equipment: "pool", activityKey: "swimming", fr: "Endurance continue", en: "Continuous endurance swim", mode: "time", seconds: 1200, sets: 1, rest: 0, distanceM: 800 },
    { key: "boxing_heavy_bag", goal: "boxing", equipment: "boxing", activityKey: "boxing", fr: "Sac de frappe", en: "Heavy bag rounds", mode: "time", seconds: 180, sets: 6, rest: 60, metValue: 12.8 },
    { key: "boxing_speed_bag", goal: "boxing", equipment: "boxing", activityKey: "boxing", fr: "Poire de vitesse", en: "Speed bag", mode: "time", seconds: 120, sets: 5, rest: 45, metValue: 5.8 },
    { key: "boxing_shadow", goal: "boxing", equipment: "bodyweight", activityKey: "boxing", fr: "Shadow boxing", en: "Shadow boxing", mode: "time", seconds: 180, sets: 5, rest: 45, metValue: 7.0 },
    { key: "boxing_mitts", goal: "boxing", equipment: "boxing", activityKey: "boxing", fr: "Pattes d ours", en: "Focus mitts", mode: "time", seconds: 180, sets: 6, rest: 60, metValue: 8.0 },
    { key: "boxing_light_sparring", goal: "boxing", equipment: "boxing", activityKey: "boxing", fr: "Sparring leger", en: "Light sparring", mode: "time", seconds: 180, sets: 4, rest: 90, metValue: 8.2 },
    { key: "boxing_footwork", goal: "boxing", equipment: "bodyweight", activityKey: "boxing", fr: "Footwork boxe", en: "Boxing footwork", mode: "time", seconds: 120, sets: 6, rest: 45, metValue: 6.5 },
    { key: "boxing_slips", goal: "boxing", equipment: "bodyweight", activityKey: "boxing", fr: "Esquives et slips", en: "Slips and defensive drills", mode: "time", seconds: 90, sets: 6, rest: 30, metValue: 5.8 },
    { key: "boxing_burpees", goal: "boxing", equipment: "bodyweight", activityKey: "hiit", fr: "Burpees boxe", en: "Boxing burpees", mode: "reps", reps: 8, sets: 5, rest: 45, metValue: 8.5 },
    { key: "boxing_jump_rope", goal: "boxing", equipment: "rope", activityKey: "jump_rope", fr: "Corde a sauter boxe", en: "Boxing jump rope", mode: "time", seconds: 180, sets: 5, rest: 45, metValue: 11.8 },
    { key: "boxing_bag_combo_rounds", goal: "boxing", equipment: "boxing", activityKey: "boxing", fr: "Rounds combo au sac", en: "Heavy bag combo rounds", mode: "time", seconds: 180, sets: 8, rest: 60, metValue: 12.8 },
    { key: "pullup", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Tractions", en: "Pull-up", mode: "reps", reps: 6, sets: 4, rest: 90, metValue: 6.0 },
    { key: "chinup", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Chin-up", en: "Chin-up", mode: "reps", reps: 6, sets: 4, rest: 90, metValue: 6.0 },
    { key: "australian_pullup", goal: "strength", equipment: "bodyweight", activityKey: "bodyweight_strength", fr: "Tractions australiennes", en: "Australian pull-up", mode: "reps", reps: 10, sets: 3, rest: 75, metValue: 5.4 },
    { key: "handstand_hold", goal: "strength", equipment: "bodyweight", activityKey: "plank_core", fr: "Appui renverse tenu", en: "Handstand hold", mode: "time", seconds: 30, sets: 4, rest: 75, metValue: 5.0 },
    { key: "box_jump", goal: "cardio", equipment: "bodyweight", activityKey: "hiit", fr: "Box jump", en: "Box jump", mode: "reps", reps: 10, sets: 5, rest: 60, metValue: 8.0 },
    { key: "wall_ball", goal: "cardio", equipment: "mixed", activityKey: "hiit", fr: "Wall ball", en: "Wall ball", mode: "reps", reps: 15, sets: 5, rest: 60, metValue: 7.6 },
  ];
