// PCG-inspired families, personal analytical subdivisions; not a statutory business ledger.
export const CHART = Object.freeze([
  {"code": "108000", "label": "Patrimoine personnel apporté", "kind": "equity", "group": "Capitaux propres"},
  {"code": "110000", "label": "Résultats antérieurs confirmés", "kind": "equity", "group": "Capitaux propres"},
  {"code": "120000", "label": "Résultat confirmé de l'exercice", "kind": "equity", "group": "Capitaux propres"},
  {"code": "164100", "label": "Emprunts bancaires à plus d'un an", "kind": "liability", "group": "Dettes financières"},
  {"code": "164200", "label": "Échéances d'emprunts à moins d'un an", "kind": "liability", "group": "Dettes financières"},
  {"code": "165000", "label": "Dépôts reçus à restituer", "kind": "liability", "group": "Autres dettes"},
  {"code": "168000", "label": "Autres emprunts", "kind": "liability", "group": "Dettes financières"},
  {"code": "211000", "label": "Terrains", "kind": "asset", "group": "Immobilisations"},
  {"code": "213000", "label": "Constructions", "kind": "asset", "group": "Immobilisations"},
  {"code": "218100", "label": "Aménagements", "kind": "asset", "group": "Immobilisations"},
  {"code": "218200", "label": "Véhicules", "kind": "asset", "group": "Immobilisations"},
  {"code": "218310", "label": "Ordinateurs", "kind": "asset", "group": "Immobilisations"},
  {"code": "218320", "label": "Téléphones et tablettes", "kind": "asset", "group": "Immobilisations"},
  {"code": "218330", "label": "Matériel photo et vidéo", "kind": "asset", "group": "Immobilisations"},
  {"code": "218400", "label": "Mobilier", "kind": "asset", "group": "Immobilisations"},
  {"code": "218800", "label": "Autres équipements", "kind": "asset", "group": "Immobilisations"},
  {"code": "261000", "label": "Titres de participation", "kind": "asset", "group": "Placements"},
  {"code": "271000", "label": "Titres immobilisés", "kind": "asset", "group": "Placements"},
  {"code": "275000", "label": "Dépôts et cautions versés", "kind": "asset", "group": "Créances"},
  {"code": "281820", "label": "Amortissement des véhicules", "kind": "contraAsset", "group": "Amortissements cumulés"},
  {"code": "281830", "label": "Amortissement informatique et matériel", "kind": "contraAsset", "group": "Amortissements cumulés"},
  {"code": "281840", "label": "Amortissement du mobilier", "kind": "contraAsset", "group": "Amortissements cumulés"},
  {"code": "281880", "label": "Autres amortissements cumulés", "kind": "contraAsset", "group": "Amortissements cumulés"},
  {"code": "401000", "label": "Factures à payer", "kind": "liability", "group": "Dettes courantes"},
  {"code": "411000", "label": "Créances à encaisser", "kind": "asset", "group": "Créances"},
  {"code": "431000", "label": "Cotisations sociales à payer", "kind": "liability", "group": "Dettes courantes"},
  {"code": "447000", "label": "Impôts et taxes à payer", "kind": "liability", "group": "Dettes courantes"},
  {"code": "467100", "label": "Autres créances personnelles", "kind": "asset", "group": "Créances"},
  {"code": "467200", "label": "Autres dettes personnelles", "kind": "liability", "group": "Dettes courantes"},
  {"code": "471000", "label": "Opérations patrimoniales à rapprocher", "kind": "suspense", "group": "Rapprochements"},
  {"code": "503000", "label": "Placements de trésorerie", "kind": "asset", "group": "Placements"},
  {"code": "512100", "label": "Comptes bancaires", "kind": "asset", "group": "Disponibilités"},
  {"code": "512200", "label": "Comptes en devises", "kind": "asset", "group": "Disponibilités"},
  {"code": "517000", "label": "Comptes de paiement", "kind": "asset", "group": "Disponibilités"},
  {"code": "519000", "label": "Découverts bancaires", "kind": "liability", "group": "Dettes courantes"},
  {"code": "530000", "label": "Espèces", "kind": "asset", "group": "Disponibilités"},
  {"code": "606110", "label": "Électricité", "kind": "expense", "group": "Achats courants", "keywords": "electricite,electricity"},
  {"code": "606120", "label": "Gaz et chauffage", "kind": "expense", "group": "Achats courants", "keywords": "gaz,chauffage,gas bill"},
  {"code": "606130", "label": "Eau du logement", "kind": "expense", "group": "Achats courants", "keywords": "facture eau,service eau,charges eau"},
  {"code": "606140", "label": "Carburant", "kind": "expense", "group": "Achats courants", "keywords": "carburant,essence,diesel,fuel"},
  {"code": "606310", "label": "Alimentation et courses", "kind": "expense", "group": "Achats courants", "keywords": "alimentation,nourriture,courses,supermarche,epicerie,groceries,food"},
  {"code": "606320", "label": "Hygiène et entretien courant", "kind": "expense", "group": "Achats courants", "keywords": "hygiene,savon,cosmetique,produits entretien"},
  {"code": "606330", "label": "Pharmacie et médicaments", "kind": "expense", "group": "Achats courants", "keywords": "pharmacie,medicaments,medicament,pharmacy"},
  {"code": "606340", "label": "Habillement et chaussures", "kind": "expense", "group": "Achats courants", "keywords": "vetement,vetements,chaussures,habillement,clothing,shoes"},
  {"code": "606350", "label": "Petit équipement non immobilisé", "kind": "expense", "group": "Achats courants", "keywords": "petit equipement,petit materiel"},
  {"code": "606360", "label": "Fournitures administratives", "kind": "expense", "group": "Achats courants", "keywords": "papeterie,fournitures bureau,impression"},
  {"code": "606370", "label": "Livres et documentation", "kind": "expense", "group": "Achats courants", "keywords": "livre,livres,documentation"},
  {"code": "606390", "label": "Autres achats quotidiens", "kind": "expense", "group": "Achats courants", "keywords": "vie quotidienne,achats quotidiens"},
  {"code": "613210", "label": "Loyer du logement", "kind": "expense", "group": "Services extérieurs", "keywords": "loyer,rent"},
  {"code": "613220", "label": "Hébergement hôtelier", "kind": "expense", "group": "Services extérieurs", "keywords": "hotel,hotels,auberge,auberges,guesthouse,hostel"},
  {"code": "613230", "label": "Locations de vacances", "kind": "expense", "group": "Services extérieurs", "keywords": "airbnb,location vacances,logement,hebergement,accommodation"},
  {"code": "613240", "label": "Camping", "kind": "expense", "group": "Services extérieurs", "keywords": "camping,bivouac"},
  {"code": "613510", "label": "Location de véhicule", "kind": "expense", "group": "Services extérieurs", "keywords": "location voiture,location vehicule,car rental"},
  {"code": "613520", "label": "Location de matériel", "kind": "expense", "group": "Services extérieurs", "keywords": "location materiel,location equipement"},
  {"code": "614000", "label": "Charges locatives", "kind": "expense", "group": "Services extérieurs", "keywords": "charges locatives,copropriete"},
  {"code": "615210", "label": "Entretien du logement", "kind": "expense", "group": "Services extérieurs", "keywords": "entretien logement,travaux logement,reparation logement"},
  {"code": "615510", "label": "Entretien des véhicules", "kind": "expense", "group": "Services extérieurs", "keywords": "garage,pneu,pneus,mecanique,reparation voiture"},
  {"code": "615520", "label": "Réparation de matériel", "kind": "expense", "group": "Services extérieurs", "keywords": "reparation ordinateur,reparation telephone,reparation materiel"},
  {"code": "615590", "label": "Autres entretiens et réparations", "kind": "expense", "group": "Services extérieurs", "keywords": "entretien,reparation,reparations,maintenance"},
  {"code": "616110", "label": "Assurance habitation", "kind": "expense", "group": "Services extérieurs", "keywords": "assurance habitation,home insurance"},
  {"code": "616120", "label": "Assurance automobile", "kind": "expense", "group": "Services extérieurs", "keywords": "assurance voiture,assurance auto,car insurance"},
  {"code": "616130", "label": "Assurance santé", "kind": "expense", "group": "Services extérieurs", "keywords": "assurance sante,mutuelle,health insurance"},
  {"code": "616140", "label": "Assurance voyage", "kind": "expense", "group": "Services extérieurs", "keywords": "assurance voyage,travel insurance"},
  {"code": "616190", "label": "Autres assurances", "kind": "expense", "group": "Services extérieurs", "keywords": "assurance,assurances,insurance"},
  {"code": "618110", "label": "Formation et scolarité", "kind": "expense", "group": "Services extérieurs", "keywords": "formation,formations,etudes,scolarite,training"},
  {"code": "618120", "label": "Logiciels et services numériques", "kind": "expense", "group": "Services extérieurs", "keywords": "logiciel,cloud,software"},
  {"code": "618190", "label": "Autres projets personnels", "kind": "expense", "group": "Services extérieurs", "keywords": "projet personnel"},
  {"code": "622610", "label": "Consultations médicales", "kind": "expense", "group": "Services extérieurs", "keywords": "medecin,consultation,consultations,sante,medical,health"},
  {"code": "622620", "label": "Soins dentaires", "kind": "expense", "group": "Services extérieurs", "keywords": "dentiste,dentaire"},
  {"code": "622630", "label": "Optique et soins spécialisés", "kind": "expense", "group": "Services extérieurs", "keywords": "optique,lunettes,kine,soins"},
  {"code": "622640", "label": "Conseil et honoraires", "kind": "expense", "group": "Services extérieurs", "keywords": "avocat,conseil,comptable,honoraires"},
  {"code": "625110", "label": "Avion", "kind": "expense", "group": "Déplacements et repas", "keywords": "avion,vol,flight,transport internationale"},
  {"code": "625120", "label": "Train et métro", "kind": "expense", "group": "Déplacements et repas", "keywords": "train,metro,tram,rail"},
  {"code": "625130", "label": "Bus et autocar", "kind": "expense", "group": "Déplacements et repas", "keywords": "bus,autocar"},
  {"code": "625140", "label": "Taxi et VTC", "kind": "expense", "group": "Déplacements et repas", "keywords": "taxi,vtc,uber"},
  {"code": "625150", "label": "Bateau et ferry", "kind": "expense", "group": "Déplacements et repas", "keywords": "bateau,ferry"},
  {"code": "625160", "label": "Stationnement et péages", "kind": "expense", "group": "Déplacements et repas", "keywords": "parking,stationnement,peage"},
  {"code": "625190", "label": "Autres transports", "kind": "expense", "group": "Déplacements et repas", "keywords": "transport,transports,scooter,velo"},
  {"code": "625710", "label": "Restaurants et repas", "kind": "expense", "group": "Déplacements et repas", "keywords": "repas,restaurant,restaurants,dejeuner,diner,petit dejeuner"},
  {"code": "625720", "label": "Cafés et collations", "kind": "expense", "group": "Déplacements et repas", "keywords": "cafe,snack,collation,boulangerie"},
  {"code": "626110", "label": "Téléphonie et données mobiles", "kind": "expense", "group": "Communication", "keywords": "telephone,mobile,sim,recharge data,telecom"},
  {"code": "626120", "label": "Accès Internet", "kind": "expense", "group": "Communication", "keywords": "internet,wifi"},
  {"code": "626130", "label": "Courrier et expédition", "kind": "expense", "group": "Communication", "keywords": "courrier,poste,colis"},
  {"code": "626190", "label": "Autres abonnements", "kind": "expense", "group": "Communication", "keywords": "abonnement,abonnements,subscription"},
  {"code": "627110", "label": "Tenue de compte et cartes", "kind": "expense", "group": "Frais bancaires", "keywords": "frais bancaire,frais bancaires,frais carte,tenue de compte,bank fee"},
  {"code": "627120", "label": "Commissions de change", "kind": "expense", "group": "Frais bancaires", "keywords": "commission change,commissions change,frais change,exchange fee"},
  {"code": "627130", "label": "Frais de retrait et transfert", "kind": "expense", "group": "Frais bancaires", "keywords": "frais retrait,frais transfert"},
  {"code": "635110", "label": "Impôt sur le revenu", "kind": "expense", "group": "Impôts et taxes", "keywords": "impot revenu,income tax"},
  {"code": "635120", "label": "Taxes locales et foncières", "kind": "expense", "group": "Impôts et taxes", "keywords": "taxe fonciere,taxe habitation,taxes locales"},
  {"code": "635130", "label": "Visas et droits administratifs", "kind": "expense", "group": "Impôts et taxes", "keywords": "visa,consulaire,demarches,frontiere"},
  {"code": "635190", "label": "Autres impôts et taxes", "kind": "expense", "group": "Impôts et taxes", "keywords": "impot,impots,taxe,taxes,fiscalite"},
  {"code": "646000", "label": "Cotisations sociales personnelles", "kind": "expense", "group": "Cotisations", "keywords": "cotisation sociale,urssaf"},
  {"code": "651110", "label": "Activités culturelles", "kind": "expense", "group": "Vie personnelle", "keywords": "cinema,musee,culture,culturel"},
  {"code": "651120", "label": "Sport et activités", "kind": "expense", "group": "Vie personnelle", "keywords": "sport,sportive,activite,activites,excursion,excursions"},
  {"code": "651130", "label": "Sorties et divertissements", "kind": "expense", "group": "Vie personnelle", "keywords": "sortie,sorties,loisir,loisirs,fete,bar,bars,evenement"},
  {"code": "651140", "label": "Souvenirs", "kind": "expense", "group": "Vie personnelle", "keywords": "souvenir,souvenirs"},
  {"code": "651150", "label": "Cadeaux", "kind": "expense", "group": "Vie personnelle", "keywords": "cadeau,cadeaux,gift"},
  {"code": "651160", "label": "Dons et solidarité", "kind": "expense", "group": "Vie personnelle", "keywords": "don,dons,donation"},
  {"code": "651170", "label": "Blanchisserie et services personnels", "kind": "expense", "group": "Vie personnelle", "keywords": "laundry,blanchisserie,coiffeur"},
  {"code": "658900", "label": "Charges à classifier", "kind": "expense", "group": "À classifier"},
  {"code": "661100", "label": "Intérêts d'emprunts", "kind": "expense", "group": "Charges financières", "keywords": "interet emprunt,interets emprunt,loan interest"},
  {"code": "661600", "label": "Agios et intérêts bancaires", "kind": "expense", "group": "Charges financières", "keywords": "agios,interets debiteurs"},
  {"code": "666000", "label": "Pertes de change réalisées", "kind": "expense", "group": "Charges financières", "keywords": "perte change,pertes change"},
  {"code": "671100", "label": "Amendes et pénalités", "kind": "expense", "group": "Charges exceptionnelles", "keywords": "amende,amendes,penalite,penalites"},
  {"code": "681120", "label": "Dotations aux amortissements", "kind": "expense", "group": "Amortissements"},
  {"code": "706100", "label": "Prestations et activité indépendante", "kind": "income", "group": "Revenus d'activité", "keywords": "freelance,honoraires,prestations,independant"},
  {"code": "752100", "label": "Loyers et revenus locatifs", "kind": "income", "group": "Revenus patrimoniaux", "keywords": "revenu locatif,revenus locatifs,loyer percu,loyers percus,rente locative"},
  {"code": "758110", "label": "Salaires reçus", "kind": "income", "group": "Revenus personnels", "keywords": "salaire,salaires,salary,wage,travail,paye,remuneration"},
  {"code": "758120", "label": "Primes et bonus reçus", "kind": "income", "group": "Revenus personnels", "keywords": "prime,primes,bonus"},
  {"code": "758210", "label": "Allocations et aides reçues", "kind": "income", "group": "Revenus personnels", "keywords": "allocation,allocations,aide,aides,chomage"},
  {"code": "758220", "label": "Pensions et retraites reçues", "kind": "income", "group": "Revenus personnels", "keywords": "pension,retraite"},
  {"code": "758310", "label": "Dons et cadeaux reçus", "kind": "income", "group": "Revenus personnels", "keywords": "don,dons,cadeau,cadeaux,gift"},
  {"code": "758900", "label": "Revenus à classifier", "kind": "income", "group": "À classifier"},
  {"code": "761100", "label": "Dividendes reçus", "kind": "income", "group": "Produits financiers", "keywords": "dividende,dividendes,dividend"},
  {"code": "762100", "label": "Intérêts de placements", "kind": "income", "group": "Produits financiers", "keywords": "interet,interets,interest"},
  {"code": "766000", "label": "Gains de change réalisés", "kind": "income", "group": "Produits financiers", "keywords": "gain change,gains change"},
  {"code": "486000", "label": "Charges constatées d’avance", "kind": "asset", "group": "Régularisations"},
  {"code": "487000", "label": "Produits constatés d’avance", "kind": "liability", "group": "Régularisations"}
]);
export const ACCOUNTS = Object.freeze(Object.fromEntries(CHART.map(a => [a.code, a.label])));
export const accountInfo = code => CHART.find(a => a.code === code);
export const selectableAccounts = () => CHART.filter(a => ["income", "expense", "suspense"].includes(a.kind) && a.code !== "681120");
