import { money } from './accountingRules.js';
import { ACCOUNTS, mappingKey, resolveAccount, inferAccount } from './accountingMapping.js';

export const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const tabs = { summary: 'Synthèse', result: 'Compte de résultat', balance: 'Bilan', entries: 'Mouvements', settings: 'Paramétrage' };
const button = (label, attributes = '') => `<button type="button" class="btn" ${attributes}>${esc(label)}</button>`;
const amount = (value, currency) => `${money(value)}${Number.isFinite(value) ? ` ${esc(currency)}` : ''}`;
const difference = (a, b) => Number.isFinite(a) && Number.isFinite(b) ? a - b : null;
const fxDetail = item => item.originalCurrency && item.originalCurrency !== item.currency ? `<p class="tb-accounting-muted">Origine : ${amount(item.originalAmount, item.originalCurrency)} · ${item.originalAmount === 0 ? 'Montant nul : conversion sans effet' : item.fxRate ? `1 ${esc(item.originalCurrency)} = ${Number(item.fxRate).toLocaleString('fr-FR', { maximumFractionDigits: 8 })} ${esc(item.currency)} · taux du ${esc(item.fxDate)} · ${esc(item.fxSource)}` : 'Taux FX indisponible pour cette date'}</p>` : '';
const row = (label, value, currency) => `<div class="tb-accounting-line"><span>${esc(label)}</span><strong>${amount(value, currency)}</strong></div>`;
const sourceButton = (item, currency) => `<button type="button" class="tb-accounting-movement" data-ac-source="${esc(item.id)}"><span><strong>${esc(item.label)}</strong><small>${esc(item.date)}${item.account ? ` · ${esc(item.account)} · ${esc(ACCOUNTS[item.account])}` : ''}${item.subcategory ? ` · ${esc(item.subcategory)}` : ''}</small>${item.originalCurrency && item.originalCurrency !== currency ? `<small>Origine : ${amount(item.originalAmount, item.originalCurrency)}</small>` : ''}</span><span>${amount(item.amount, item.currency || currency)} <span aria-hidden="true">›</span></span></button>`;
const list = (items, currency) => items.map(i => sourceButton(i, currency)).join('') || '<p class="tb-accounting-muted">Aucun mouvement sur cette période.</p>';

const total = items => items.every(r => Number.isFinite(r.amount)) ? items.reduce((n, r) => n + Math.round(r.amount * 100), 0) / 100 : null;
function groupedMovements(items, currency) {
  const groups = new Map();
  for (const item of items) {
    const key = JSON.stringify([item.category, item.subcategory || '']);
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(item);
  }
  return [...groups.values()].sort((a, b) => a[0].category.localeCompare(b[0].category, 'fr', { numeric: true }) || (a[0].subcategory || '').localeCompare(b[0].subcategory || '', 'fr', { numeric: true })).map(rows => `<details class="tb-accounting-account"><summary><span>${esc(rows[0].category)}${rows[0].subcategory ? ` → ${esc(rows[0].subcategory)}` : ''} · ${rows.length} mouvement(s)</span><strong>${amount(total(rows), currency)}</strong></summary>${list(rows, currency)}</details>`).join('');
}
function performance(report, previous) {
  const metric = (label, value, unit, max, detail) => `<article class="tb-accounting-panel"><h3>${esc(label)}</h3><strong>${Number.isFinite(value) ? `${money(value)} ${unit}` : 'À calculer'}</strong>${Number.isFinite(value) ? `<meter min="0" max="${Math.max(max, value)}" value="${Math.max(0, value)}" aria-label="${esc(label)}">${money(value)} ${unit}</meter>` : ''}<p class="tb-accounting-muted">${esc(detail)}</p></article>`;
  const flows = [['Revenus', report.income], ['Charges hors amortissements', report.cashExpenses], ['Amortissements', report.depreciation], ['Résultat', report.result]];
  const scale = Math.max(1, ...flows.map(([, v]) => Math.abs(v || 0)));
  return `<section aria-label="Indicateurs de performance"><h3>Performance de la période</h3><div class="tb-accounting-columns">${metric('Taux d’épargne courant', report.savingRate, '%', 100, 'Excédent hors amortissements / revenus. Une valeur négative indique un déficit.')}${metric('Autonomie de trésorerie', report.autonomyMonths, 'mois', 12, 'Trésorerie nette positive / charges mensuelles moyennes hors amortissements, calculées sur les jours écoulés de la période. Sans projection de revenus.')}${metric('Poids des dettes', report.debtRatio, '%', 100, 'Dettes et découverts / actif recensé. À calculer lorsque l’actif est nul ; peut dépasser 100 %.')}${metric('Marge personnelle', report.income > 0 && report.result !== null ? report.result / report.income * 100 : null, '%', 100, 'Résultat après amortissements / revenus. Sans revenus, le ratio ne peut pas être calculé.')}</div></section><section class="tb-accounting-panel" aria-label="Composition du résultat"><h3>Revenus, charges et résultat</h3>${flows.map(([label, value]) => `<div class="tb-accounting-flow">${row(label, value, report.currency)}${Number.isFinite(value) ? `<meter min="0" max="${scale}" value="${Math.abs(value)}" aria-label="${esc(label)} : ${esc(amount(value, report.currency))}"></meter>` : ''}</div>`).join('')}${row('Évolution du résultat en valeur', difference(report.result, previous.result), report.currency)}<p class="tb-accounting-muted">Comparaison avec ${esc(previous.start)} → ${esc(previous.end)}. Les barres représentent l’amplitude ; les montants conservent leur signe. ${report.unconfirmed.length ? 'Bilan provisoire : compléments à confirmer.' : 'Ratios calculés sur les données recensées.'}</p></section>`;
}

function summary(report, previous) {
  const { currency: c } = report;
  const card = (label, value, detail, tab) => `<button type="button" class="tb-accounting-kpi" data-ac-tab="${tab}"><span>${esc(label)}</span><strong>${value}</strong><small>${esc(detail)} →</small></button>`;
  return `<div class="tb-accounting-kpis">${card('Résultat personnel', amount(report.result, c), 'Revenus − charges − amortissements', 'result')}${card('Trésorerie actuelle', amount(report.cash, c), 'Somme des soldes des comptes, découverts inclus', 'balance')}${card('Patrimoine net recensé', amount(report.netWorth, c), report.unconfirmed.length ? 'Estimation · compléments à confirmer' : 'Trésorerie + biens nets + créances − dettes', 'balance')}${card('Taux d’épargne courant', report.savingRate === null ? 'Non disponible' : `${money(report.savingRate)} %`, '(Revenus − charges hors amortissements) / revenus', 'result')}</div>
    <section class="tb-accounting-panel"><h3>Comprendre ta situation</h3>${row('Revenus de la période', report.income, c)}${row('Charges hors amortissements', difference(report.expenses, report.depreciation), c)}${row('Amortissements de la période', report.depreciation, c)}<p class="tb-accounting-muted">Les achats de biens liés à Patrimoine sont répartis par amortissement. Les virements internes ne changent pas le résultat. Le taux d’épargne exclut les achats de biens et remboursements de capital : ce n’est pas la variation de trésorerie.</p></section>${performance(report, previous)}`;
}

function resultView(report, previous) {
  const group = (kind, label) => {
    const codes = [...new Set([...report.entries, ...previous.entries].filter(e => e.kind === kind).map(e => e.account))].sort();
    const sum = (r, code) => total(r.entries.filter(e => e.account === code));
    return `<section class="tb-accounting-panel"><h3>${label}</h3>${codes.map(code => `<details class="tb-accounting-account"><summary><span>${esc(code)} · ${esc(ACCOUNTS[code])}</span><strong>${amount(sum(report, code), report.currency)}</strong></summary><p class="tb-accounting-muted">Période comparée : ${amount(sum(previous, code), report.currency)}</p>${groupedMovements(report.entries.filter(e => e.account === code), report.currency)}</details>`).join('') || '<p>Aucun mouvement.</p>'}</section>`;
  };
  return `<p class="tb-accounting-muted">Comparaison : ${esc(previous.start)} au ${esc(previous.end)}. Résultat basé sur les opérations réglées et les dotations calculées, à vérifier selon les alertes.</p>${group('expense', 'Charges')}${group('income', 'Revenus')}
    <section class="tb-accounting-panel">${row('Résultat de la période', report.result, report.currency)}${row('Résultat de la période comparée', previous.result, report.currency)}${row('Écart', difference(report.result, previous.result), report.currency)}</section>`;
}

function balanceView(report) {
  const c = report.currency;
  const positives = report.walletRows.filter(w => w.amount >= 0 && w.amount !== null);
  const negatives = report.walletRows.filter(w => w.amount < 0);
  const { availableCash: knownCash, overdraft, totalAssets: assetTotal, totalFunding: fundingTotal } = report;
  return `<p class="tb-accounting-muted">Situation actuelle au ${esc(report.today)} · périmètre du voyage actif et biens sans voyage. Ce bilan ne reconstitue pas une clôture historique.</p>
    <div class="tb-accounting-columns"><section class="tb-accounting-panel"><h3>Actif · ce que tu possèdes</h3><details class="tb-accounting-account"><summary><span>Comptes disponibles</span><strong>${amount(knownCash, c)}</strong></summary>${list([...positives, ...report.walletRows.filter(w => w.amount === null)], c)}</details><details class="tb-accounting-account"><summary><span>Biens à leur valeur nette</span><strong>${amount(report.netAssets, c)}</strong></summary>${report.assetRows.map(a => `<div>${sourceButton(a, c)}<p class="tb-accounting-muted">Brut ${amount(a.gross, c)} · amorti ${amount(a.accumulated, c)} · quote-part ${money(a.share * 100)} %</p></div>`).join('') || '<p>Aucun bien recensé dans ce périmètre.</p>'}</details>${row('Créances complémentaires déclarées', report.receivable, c)}${row('Total actif recensé', assetTotal, c)}</section>
    <section class="tb-accounting-panel"><h3>Passif · patrimoine net et dettes</h3>${row('Patrimoine net recensé', report.netWorth, c)}<details class="tb-accounting-account"><summary><span>Découverts des comptes</span><strong>${amount(overdraft, c)}</strong></summary>${list(negatives, c)}</details>${row('Autres dettes déclarées', report.debt, c)}${row('Total passif recensé', fundingTotal, c)}<p class="tb-accounting-muted">Patrimoine net = actif recensé − découverts − autres dettes. Les placements absents de Patrimoine et les soldes Trip non réglés ne sont pas ajoutés automatiquement.</p></section></div>
    ${row('Écart actif − passif', difference(assetTotal, fundingTotal), c)}${report.unconfirmed.length || report.debt === null || report.receivable === null ? `<section class="tb-accounting-panel"><h3>Compléter le bilan</h3><p>Les compléments absents sont retenus à zéro pour ce bilan provisoire. Les montants déjà saisis sont conservés avec leur date. Confirme zéro ou saisis les dettes et créances manquantes.</p>${button('Renseigner les soldes', 'data-ac-tab="settings"')}</section>` : '<p class="tb-accounting-muted">Les montants déclarés doivent couvrir uniquement ce périmètre et cette devise, sans recompter les découverts déjà inclus.</p>'}`;
}

function settingsView(report, data, settings) {
  const pairs = [...new Map((data.transactions || []).filter(t => ['income', 'expense'].includes(t.type)).map(t => [mappingKey(t), t])).entries()].sort((a, b) => resolveAccount(a[1], settings).account.localeCompare(resolveAccount(b[1], settings).account, 'fr', { numeric: true }) || (a[1].category || '').localeCompare(b[1].category || '', 'fr', { numeric: true }) || (a[1].subcategory || '').localeCompare(b[1].subcategory || '', 'fr', { numeric: true }));
  const declarations = report.declarationCurrencies.map(cur => {
    const declared = settings.balances?.[cur] || {};
    return `<fieldset data-ac-balance="${esc(cur)}"><legend>Soldes complémentaires · ${esc(cur)} · ${esc(report.today)}</legend><div class="tb-accounting-filters"><label>Autres dettes<input name="debt:${esc(cur)}" data-ac-debt type="number" min="0" step="0.01" value="${esc(declared.debt ?? '')}" placeholder="À renseigner"></label><label>Créances complémentaires<input name="receivable:${esc(cur)}" data-ac-receivable type="number" min="0" step="0.01" value="${esc(declared.receivable ?? '')}" placeholder="À renseigner"></label></div>${declared.asOf ? `<p class="tb-accounting-muted">Dernière déclaration : ${esc(declared.asOf)}</p>` : ''}</fieldset>`;
  }).join('');
  const mappings = pairs.map(([key, tx], i) => {
    const resolved = resolveAccount(tx, settings), inferred = inferAccount(tx);
    const selected = ['manual', 'initial'].includes(resolved.origin) ? resolved.account : 'auto';
    return `<label class="tb-accounting-mapping" for="ac-map-${i}"><span>${esc(tx.category || 'Sans catégorie')}${tx.subcategory ? ` → ${esc(tx.subcategory)}` : ''} · ${tx.type === 'income' ? 'revenu' : 'charge'}<small>${esc(resolved.origin === 'manual' ? 'Manuel' : resolved.origin === 'review' ? 'À vérifier' : resolved.origin === 'initial' ? 'Déduction initiale' : 'Déduit automatiquement')} · ${esc(resolved.reason)}</small></span><select id="ac-map-${i}" data-ac-mapping="${esc(key)}"><option value="auto"${selected === 'auto' ? ' selected' : ''}>Auto → ${esc(inferred.account)} · ${esc(ACCOUNTS[inferred.account])}</option>${Object.entries(ACCOUNTS).filter(([code]) => code === '471' || code !== '681' && code.startsWith(tx.type === 'income' ? '7' : '6')).map(([code, label]) => `<option value="${code}"${selected === code ? ' selected' : ''}>${code} · ${esc(label)}</option>`).join('')}</select></label>`;
  }).join('');
  return `<form id="tb-accounting-settings" class="tb-accounting-panel"><h3>Paramétrage personnel</h3><p>Ces réglages restent sur cet appareil, pour ce compte et ce voyage. Ils ne modifient pas les transactions et ne sont pas synchronisés ni inclus dans l’export général.</p><p class="tb-accounting-muted">Renseigne les soldes complémentaires dans leur devise d’origine, sans recompter les comptes et biens. Zéro confirme leur absence ; une case vide est retenue à zéro provisoire, à confirmer. La consolidation les convertit au taux du bilan. Les valeurs saisies restent utilisées ; leur date indique quand les reconfirmer.</p>${declarations}<fieldset><legend>Catégories et sous-catégories → comptes personnels</legend><p class="tb-accounting-muted">Le classement initial est complété une seule fois sur cet appareil ; tes affectations existantes sont conservées. Les comptes puis catégories et sous-catégories sont triés par ordre croissant. « Auto » réactive la déduction ; les cas ambigus restent à vérifier. Ces codes sont des regroupements de gestion personnelle.</p>${mappings || '<p>Les catégories apparaîtront avec tes transactions.</p>'}</fieldset><button class="btn primary" type="submit">Enregistrer et recalculer</button></form>
    <section class="tb-accounting-panel"><h3>Règles de calcul et FX</h3><p>Opérations : taux FX journalier à la date de l’opération. Comptes, dettes et créances : taux à la date du bilan. Biens et amortissements : taux historique d’acquisition conservé.</p><p>Le dernier taux publié antérieur est utilisé dans une limite de sept jours, notamment les week-ends. Un taux manuel FX daté peut servir de repli. La fiche source affiche montant d’origine, taux, date et provenance ; un taux manquant rend le total concerné non disponible.</p><p>Quotes-parts Trip et amortissements sont distingués des débits réels. Les ventes, financements et changements de propriétaire restent à rapprocher. Les amortissements sont linéaires en fin de mois dès le mois d’achat, à ta quote-part.</p>${button('Paramétrer les biens', 'data-ac-open="assets"')}${button('Paramétrer les comptes / FX', 'data-ac-open="settings"')}</section>`;
}

export function renderAccounting({ report, previous, data, settings, ui, currencies, scopeName, status = '' }) {
  const all = [...report.entries, ...report.excluded, ...report.assetRows, ...report.walletRows];
  const source = all.find(r => r.id === ui.source);
  let content;
  if (source) {
    const raw = source.sourceType === 'transaction' ? data.transactions.find(t => String(t.id) === String(source.sourceId)) : source.sourceType === 'asset' ? data.assets.find(a => String(a.id) === String(source.sourceId)) : null;
    content = `<section class="tb-accounting-panel" tabindex="-1" id="tb-accounting-detail">${button(`← ${tabs[ui.tab]}`, 'data-ac-back')}<h3>${esc(source.label)}</h3>${row('Montant retenu / solde', source.amount, source.currency || report.currency)}${fxDetail(source)}${source.account ? `<p>Compte ${esc(source.account)} · ${esc(ACCOUNTS[source.account])} · ${esc(source.reason || 'Calcul automatique')}</p>` : ''}<p>${esc(source.date)} · ${esc(source.sourceType === 'asset' ? 'Bien du patrimoine' : source.sourceType === 'wallet' ? 'Compte' : 'Transaction')}</p><p>${esc(source.explanation || source.reason)}</p>${raw && source.sourceType === 'transaction' ? `<p>Catégorie : ${esc(raw.category || 'Sans catégorie')}${raw.subcategory ? ` → ${esc(raw.subcategory)}` : ''} · ${raw.type === 'income' ? 'revenu' : 'dépense'}</p>` : ''}<details><summary>Traçabilité</summary><p>Source : ${esc(source.sourceId)}</p><p>Calcul : ${esc(source.id)}</p></details>${source.sourceType === 'transaction' ? button('Ouvrir la transaction', `data-ac-transaction="${esc(source.sourceId)}"`) : button(source.sourceType === 'asset' ? 'Ouvrir Patrimoine' : 'Ouvrir les comptes', `data-ac-open="${source.sourceType === 'asset' ? 'assets' : 'dashboard'}"`)}</section>`;
  } else if (ui.tab === 'summary') content = summary(report, previous);
  else if (ui.tab === 'result') content = resultView(report, previous);
  else if (ui.tab === 'balance') content = balanceView(report);
  else if (ui.tab === 'settings') content = settingsView(report, data, settings);
  else content = `<section class="tb-accounting-panel"><h3>Mouvements retenus (${report.entries.length})</h3><p class="tb-accounting-muted">Détail calculé à partir des sources ; ce relevé n’est pas un journal comptable validé.</p>${list(report.entries, report.currency)}</section><section class="tb-accounting-panel"><h3>Écartés du résultat (${report.excluded.length})</h3>${report.excluded.map(e => `${sourceButton(e, report.currency)}<p class="tb-accounting-muted">${esc(e.reason)}</p>`).join('') || '<p>Aucun mouvement écarté.</p>'}</section>`;
  return `<div class="tb-accounting"><div class="tb-accounting-head"><div><span class="tb-accounting-kicker">📒 Finances personnelles</span><h2>Comptabilité</h2><p>${esc(scopeName)} · vue de gestion personnelle · consolidation FX</p></div>${button('Actualiser', 'data-ac-refresh')}</div><form id="tb-accounting-period" class="tb-accounting-filters"><label>Du<input type="date" name="start" required value="${esc(report.start)}"></label><label>Au<input type="date" name="end" required value="${esc(report.end)}"></label><label>Devise de présentation<select name="currency">${currencies.map(c => `<option${c === report.currency ? ' selected' : ''}>${esc(c)}</option>`).join('')}</select></label><label>Affichage<select name="mode"><option value="consolidated"${report.mode !== 'native' ? ' selected' : ''}>Consolidé (FX)</option><option value="native"${report.mode === 'native' ? ' selected' : ''}>Devise seule</option></select></label><button class="btn" type="submit">Appliquer</button></form><p class="tb-accounting-muted">Résultat : ${esc(report.start)} → ${esc(report.end)} · Bilan : ${esc(report.today)} · ${report.mode === 'native' ? 'devise seule, sans conversion' : `toutes les devises consolidées en ${esc(report.currency)} · taux FX datés`}</p><nav class="tb-accounting-tabs" aria-label="Vues comptables">${Object.entries(tabs).map(([key, label]) => button(label, `data-ac-tab="${key}" aria-pressed="${key === ui.tab}"`)).join('')}</nav><div role="status" class="tb-accounting-status">${esc(status)}</div>${report.warnings.length ? `<details class="tb-accounting-notice"><summary>${report.warnings.length} point(s) à vérifier · chiffres provisoires</summary><ul>${report.warnings.map(w => `<li>${esc(w)}</li>`).join('')}</ul></details>` : ''}<main class="tb-accounting-content">${content}</main></div>`;
}
