import { describe, expect, it } from 'vitest';
import fs from 'node:fs';

describe('settings view extraction contract', () => {
  const main = fs.readFileSync('src/main.js', 'utf8');
  const legacy = fs.readFileSync('public/legacy/js/14_settings_periods_ui.js', 'utf8');

  it('exposes the Settings view module to the legacy runtime', () => {
    expect(main).toContain("import * as settingsView from './features/settings/settingsView.js'");
    expect(main).toContain("import * as settingsAccountController from './features/settings/settingsAccountController.js'");
    expect(main).toContain('window.TBSettingsView');
    expect(main).toContain('...settingsView');
    expect(main).toContain('window.TBLoadSettingsCategoriesView');
    expect(main).toContain("import('./features/settings/settingsCategoriesView.js')");
    expect(main).toContain('window.TBSettingsAccountController');
    expect(main).toContain('...settingsAccountController');
  });

  it('keeps legacy Settings wrappers thin and delegated', () => {
    expect(legacy).toContain('window.TBSettingsView?.renderSettingsAccountPanel');
    expect(legacy).toContain('window.TBSettingsView?.normalizeManualFxRates');
    expect(legacy).toContain('window.TBSettingsView?.renderSettingsManualFxPanel');
    expect(legacy).toContain('window.TBSettingsView?.renderSettingsPeriodCard');
    expect(legacy).toContain('window.TBSettingsView?.renderSettingsPeriodReference');
    expect(legacy).toContain('window.TBSettingsView?.renderSettingsTravelOverview');
    expect(legacy).toContain('window.TBSettingsView?.renderCreateVoyageModalBody');
    expect(legacy).toContain('window.TBSettingsView?.renderCreatePeriodModalBody');
    expect(legacy).toContain('window.TBSettingsView?.getBudgetSegmentDeleteReadiness');
    expect(legacy).toContain('window.TBSettingsAccountController?.bindSettingsAccountPanel');
    expect(legacy).toContain('window.TBSettingsView?.getSettingsPanelState');
    expect(legacy).toContain('window.TBSettingsView?.setSettingsPanelState');
    expect(legacy).toContain('window.TBSettingsView?.getSettingsCardSummary');
    expect(legacy).toContain('window.TBSettingsView?.ensureSettingsHero');
    expect(legacy).toContain('window.TBSettingsView?.decorateSettingsPanels');
    expect(legacy).toContain('window.TBLoadSettingsCategoriesView');
    expect(legacy).toContain('window.TBSettingsCategoriesView?.renderSettingsCategoriesList');
    expect(legacy).toContain('window.TBSettingsCategoriesView?.renderGuidedCategoryModalBody');
    expect(legacy).toContain('window.TBSettingsCategoriesView?.renderGuidedSubcategoryModalBody');
    expect(legacy).toContain('window.TBSettingsCategoriesView?.prepareCategoryUpsertDraft');
    expect(legacy).toContain('window.TBSettingsCategoriesView?.notifySettingsValidation');
    expect(legacy).toContain('window.TBSettingsCategoriesView?.prepareSubcategoryEditDraft');
    expect(legacy).toContain('window.TBSettingsCategoriesView?.prepareAnalyticMappingRuleDraft');
    expect(legacy).toContain('window.TBSettingsCategoriesView?.prepareSubcategoryImportDraft');
    expect(legacy).toContain('window.TBSettingsCategoriesView?.prepareSubcategoryCreateDraft');
    expect(legacy).toContain('window.TBSettingsCategoriesView?.prepareSubcategoryMoveDraft');
    expect(legacy).not.toContain('const cards = Array.from(view.querySelectorAll');
    expect(legacy).not.toContain('box.innerHTML = `');
    expect(legacy).not.toContain('const readNotificationForm = () =>');
    expect(legacy).not.toContain('const _rememberAccount =');
    expect(legacy).not.toContain('manualPanel.innerHTML = `');
    expect(legacy).not.toContain('<button type="button" class="tb-period-head"');
    expect(legacy).not.toContain('function renderManualFxBox');
    expect(legacy).not.toContain('function tbManualFxAdd');
    expect(legacy).not.toContain('function tbManualFxDel');
    expect(legacy).not.toContain('tb-period-compare tb-period-compare--minimal');
    expect(legacy).not.toContain('tb-v11-travel-hero tb-v11-travel-hero--minimal');
    expect(legacy).not.toContain('<div class="tb-subcat-row">');
    expect(legacy).not.toContain('<details class="tb-category-card"');
    expect(legacy).not.toContain('<input id="tb-cat-create-name"');
    expect(legacy).not.toContain('<input id="tb-subcat-create-name"');
    expect(legacy).not.toContain('<input id="tb-vstart"');
    expect(legacy).not.toContain('<input id="tb-pstart"');
    expect(legacy).not.toContain('const duplicate = existingRows.find');
    expect(legacy).not.toContain('const duplicateSql = existingRows.find');
    expect(legacy).not.toContain('existingRows.reduce');
    expect(legacy).not.toContain('const swapIndex = direction ===');
    expect(legacy).not.toContain('const updates = ordered.map');
    expect(legacy).toContain('function _settingsValidationNotice');
    expect(legacy).not.toContain('if (typeof window.toastWarn === "function")');
    expect(legacy).not.toContain('if (typeof window.toastInfo === "function")');
    expect(legacy).not.toContain('throw new Error(readiness.reason || "Catégorie invalide.")');
    expect(legacy).not.toContain('const maxSort = (state.categories || []).length');
    expect(legacy).not.toContain("throw new Error(readiness.reason || 'Sous-catégorie invalide.')");
    expect(legacy).not.toContain("throw new Error('Nom de sous-catégorie vide.')");
    expect(legacy).not.toContain("throw new Error('Couleur invalide.')");
    expect(legacy).not.toContain('rows: _subcategoriesForSettings(category, true),\\n      currentId: id,\\n    });\\n    if (readiness');
    expect(legacy).not.toContain('Renommer la sous-catégorie');
    expect(legacy).not.toContain('Couleur hexadécimale optionnelle');
    expect(legacy).toContain('Modifier sous-catégorie ·');
    expect(legacy).not.toContain("const mappingStatus = (value === '__unmapped__' || value === '__inherit__')");
  });
});
