// Bridge: expose selected core modules to legacy globals
import * as money from '../core/money.js';
import * as tripRules from '../core/tripRules.js';
import * as transactionRules from '../core/transactionRules.js';
import * as transactionGuards from '../core/transactionGuards.js';
import * as transactionRpcPayload from '../core/transactionRpcPayload.js';
import * as fxRules from '../core/fxRules.js';
import * as fxDecisionRules from '../core/fxDecisionRules.js';
import * as frankfurterRules from '../core/frankfurterRules.js';
import * as inboxRules from '../core/inboxRules.js';
import * as documentRules from '../core/documentRules.js';
import * as walletBalanceRules from '../core/walletBalanceRules.js';
import * as assetRules from '../core/assetRules.js';
import * as assistantRules from '../core/assistantRules.js';
import * as notificationRules from '../core/notificationRules.js';
import * as workRules from '../core/workRules.js';
import * as bodyEnergyRules from '../core/bodyEnergyRules.js';
import * as sportLibraryRules from '../core/sportLibraryRules.js';
import * as nutritionRules from '../core/nutritionRules.js';
import * as dailyBudgetRules from '../core/dailyBudgetRules.js';
import * as recurringRules from '../core/recurringRules.js';
import * as canonicalRecords from '../core/canonicalRecords.js';
import { createEntityStore } from '../data/entityStore.js';
import { createMutationQueueStore, flushMutationQueue } from '../data/mutationQueueStore.js';
import { createSupabaseRepository } from '../data/supabaseRepository.js';
import { createTripRepository } from '../data/tripRepository.js';
import { createSportRepository } from '../data/sportRepository.js';
import { createNutritionRepository } from '../data/nutritionRepository.js';
import { createTripStore } from '../features/trip/tripStore.js';
import { createSportStore } from '../features/sport/sportStore.js';
import { createNutritionStore } from '../features/nutrition/nutritionStore.js';
import * as nutritionView from '../features/nutrition/nutritionView.js';
import * as tripView from '../features/trip/tripView.js';
import * as sportCatalog from '../features/sport/sportCatalog.js';
import * as sportProgramRules from '../features/sport/sportProgramRules.js';
import * as sportTimerView from '../features/sport/sportTimerView.js';
import * as sportTimerController from '../features/sport/sportTimerController.js';
import * as sportHistoryView from '../features/sport/sportHistoryView.js';
import * as sportSessionSandboxView from '../features/sport/sportSessionSandboxView.js';
import * as sportSessionSandboxRules from '../features/sport/sportSessionSandboxRules.js';
import * as sportProfileRules from '../features/sport/sportProfileRules.js';
import * as sportProfileView from '../features/sport/sportProfileView.js';
import * as workView from '../features/work/workView.js';
import * as assetView from '../features/assets/assetView.js';
import { storageQuota } from '../data/storageQuota.js';
import * as sportRules from '../core/sportRules.js';
import * as uiComponents from '../ui/components.js';
import '../ui/shared.css';

window.Core = window.Core || {};
window.Core.money = money;
window.Core.tripRules = tripRules;
window.Core.transactionRules = transactionRules;
window.Core.transactionGuards = transactionGuards;
window.Core.transactionRpcPayload = transactionRpcPayload;
window.Core.fxRules = fxRules;
window.Core.fxDecisionRules = fxDecisionRules;
window.Core.frankfurterRules = frankfurterRules;
window.Core.inboxRules = inboxRules;
window.Core.documentRules = documentRules;
window.Core.walletBalanceRules = walletBalanceRules;
window.Core.assetRules = assetRules;
window.Core.assistantRules = assistantRules;
window.Core.notificationRules = notificationRules;
window.Core.workRules = workRules;
window.Core.bodyEnergyRules = bodyEnergyRules;
window.Core.sportLibraryRules = sportLibraryRules;
window.Core.nutritionRules = nutritionRules;
window.Core.dailyBudgetRules = dailyBudgetRules;
window.Core.recurringRules = recurringRules;
window.Core.canonicalRecords = canonicalRecords;
window.Core.sportRules = sportRules;
window.Core.sportCatalog = sportCatalog;
window.Core.sportProgramRules = sportProgramRules;

window.Data = window.Data || {};
window.Data.appStore = window.Data.appStore || createEntityStore();
window.Data.createMutationQueueStore = createMutationQueueStore;
window.Data.flushMutationQueue = flushMutationQueue;
window.Data.supabaseRepository = window.Data.supabaseRepository || createSupabaseRepository(() => window.sb);
window.Data.tripRepository = window.Data.tripRepository || createTripRepository(() => window.sb);
window.Data.sportRepository = window.Data.sportRepository || createSportRepository(() => window.sb);
window.Data.nutritionRepository = window.Data.nutritionRepository || createNutritionRepository(() => window.sb);
window.Data.createTripStore = window.Data.createTripStore || createTripStore;
window.Data.createSportStore = window.Data.createSportStore || createSportStore;
window.Data.createNutritionStore = window.Data.createNutritionStore || createNutritionStore;
window.Data.nutritionStore = window.Data.nutritionStore || createNutritionStore({}, { entityStore: window.Data.appStore });
window.Data.storageQuota = storageQuota;
window.tbSafeLocalStorageSet = (key, value, options) => storageQuota.safeSet(window.localStorage, key, value, options);

window.UI = window.UI || {};
Object.assign(window.UI, uiComponents);
window.UI.tripView = tripView;
window.UI.sportTimerView = sportTimerView;
window.UI.sportTimerController = sportTimerController;
window.UI.sportHistoryView = sportHistoryView;
window.UI.sportSessionSandboxView = sportSessionSandboxView;
window.UI.sportProfileView = sportProfileView;
window.UI.nutritionView = nutritionView;
window.UI.workView = workView;
window.UI.assetView = assetView;
window.Core.sportSessionSandboxRules = sportSessionSandboxRules;
window.Core.sportProfileRules = sportProfileRules;

// Optional: expose money helpers directly for convenience (legacy may redefine later; that's OK)
window.moneyRound = window.moneyRound || money.moneyRound;
window.moneyAdd = window.moneyAdd || money.moneyAdd;
window.fmtMoney = window.fmtMoney || money.fmtMoney;

window.__tbBridgeReady = true;
try {
  window.dispatchEvent(new CustomEvent('tb:bridge_ready'));
} catch (_) {}
