-- Nutrition source baseline: USDA FoodData Central / common label averages; portions are app estimates for practical logging.
-- Sport MET baseline: 2024 Compendium of Physical Activities; strength exercise MET values are practical estimates around Compendium strength-training ranges.

update public.nutrition_foods nf
set
  serving_grams = v.serving_grams,
  tags = array(select distinct unnest(coalesce(nf.tags, '{}') || v.tags)),
  updated_at = now()
from (values
  ('rice_cooked', 180::numeric, array['portion_revue','source_usda_fdc']::text[]),
  ('pasta_cooked', 180::numeric, array['portion_revue','source_usda_fdc']::text[]),
  ('pasta_chicken_onion_cream', 350::numeric, array['portion_revue','plat','portion_estimee']::text[]),
  ('rice_onion_zucchini', 300::numeric, array['portion_revue','plat','portion_estimee']::text[]),
  ('chicken_breast', 130::numeric, array['portion_revue','source_usda_fdc']::text[]),
  ('egg', 60::numeric, array['portion_revue','source_usda_fdc']::text[]),
  ('fresh_cream', 30::numeric, array['portion_revue','source_usda_fdc']::text[]),
  ('muesli', 45::numeric, array['portion_revue','source_usda_fdc']::text[]),
  ('belvita', 12.5::numeric, array['portion_revue','portion_un_biscuit','source_etiquette']::text[]),
  ('bread', 60::numeric, array['portion_revue','source_usda_fdc']::text[]),
  ('burger_maison', 300::numeric, array['portion_revue','plat','portion_estimee']::text[])
) as v(key, serving_grams, tags)
where nf.key = v.key
  and nf.user_id is null;

insert into public.nutrition_foods
  (key, user_id, name, serving_grams, kcal_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fiber_per_100g, water_ml_per_100g, tags)
values
  ('baguette', null, 'Baguette', 80, 270, 9.0, 56.0, 1.5, 2.8, 35, array['pain','feculent','source_usda_fdc','portion_realiste']),
  ('whole_wheat_bread_slice', null, 'Pain complet tranche', 40, 247, 13.0, 41.0, 4.2, 7.0, 38, array['pain','feculent','source_usda_fdc','portion_realiste']),
  ('croissant', null, 'Croissant', 60, 406, 8.2, 45.8, 21.0, 2.6, 20, array['viennoiserie','petit-dej','source_usda_fdc','portion_realiste']),
  ('pain_chocolat', null, 'Pain au chocolat', 70, 420, 7.5, 45.0, 23.0, 2.5, 18, array['viennoiserie','petit-dej','source_usda_fdc','portion_realiste']),
  ('brioche_slice', null, 'Brioche tranche', 45, 355, 8.0, 53.0, 12.0, 2.0, 28, array['petit-dej','pain','source_usda_fdc','portion_realiste']),
  ('quinoa_cooked', null, 'Quinoa cuit', 150, 120, 4.4, 21.3, 1.9, 2.8, 72, array['feculent','base','source_usda_fdc','portion_realiste']),
  ('couscous_cooked', null, 'Semoule couscous cuite', 180, 112, 3.8, 23.2, 0.2, 1.4, 72, array['feculent','base','source_usda_fdc','portion_realiste']),
  ('bulgur_cooked', null, 'Boulgour cuit', 180, 83, 3.1, 18.6, 0.2, 4.5, 77, array['feculent','base','source_usda_fdc','portion_realiste']),
  ('egg_noodles_cooked', null, 'Nouilles aux oeufs cuites', 180, 138, 4.5, 25.2, 2.1, 1.2, 69, array['feculent','base','source_usda_fdc','portion_realiste']),
  ('tortilla_wheat', null, 'Tortilla ble', 60, 312, 8.2, 50.0, 8.0, 3.0, 31, array['pain','wrap','feculent','source_usda_fdc','portion_realiste']),
  ('ground_beef_5', null, 'Boeuf hache 5%', 125, 137, 21.0, 0.0, 5.0, 0.0, 69, array['proteines','boeuf','source_usda_fdc','portion_realiste']),
  ('ground_beef_15', null, 'Steak hache 15%', 125, 215, 19.0, 0.0, 15.0, 0.0, 63, array['proteines','boeuf','source_usda_fdc','portion_realiste']),
  ('turkey_ham', null, 'Blanc de dinde', 80, 110, 20.0, 2.0, 2.0, 0.0, 72, array['proteines','volaille','source_usda_fdc','portion_realiste']),
  ('cod_fillet', null, 'Cabillaud', 140, 82, 18.0, 0.0, 0.7, 0.0, 80, array['proteines','poisson','source_usda_fdc','portion_realiste']),
  ('shrimp_cooked', null, 'Crevettes cuites', 120, 99, 24.0, 0.2, 0.3, 0.0, 74, array['proteines','fruit_de_mer','source_usda_fdc','portion_realiste']),
  ('tofu_firm', null, 'Tofu ferme', 150, 144, 17.0, 2.8, 8.7, 2.3, 69, array['proteines','vegetarien','source_usda_fdc','portion_realiste']),
  ('kidney_beans_cooked', null, 'Haricots rouges cuits', 160, 127, 8.7, 22.8, 0.5, 6.4, 67, array['proteines','legumineuse','source_usda_fdc','portion_realiste']),
  ('cucumber', null, 'Concombre', 120, 15, 0.7, 3.6, 0.1, 0.5, 95, array['legume','source_usda_fdc','portion_realiste']),
  ('bell_pepper', null, 'Poivron', 120, 31, 1.0, 6.0, 0.3, 2.1, 92, array['legume','source_usda_fdc','portion_realiste']),
  ('mushroom', null, 'Champignons', 120, 22, 3.1, 3.3, 0.3, 1.0, 92, array['legume','source_usda_fdc','portion_realiste']),
  ('spinach', null, 'Epinards', 100, 23, 2.9, 3.6, 0.4, 2.2, 91, array['legume','source_usda_fdc','portion_realiste']),
  ('peas', null, 'Petits pois', 150, 84, 5.4, 15.6, 0.2, 5.5, 78, array['legume','feculent','source_usda_fdc','portion_realiste']),
  ('blueberries', null, 'Myrtilles', 125, 57, 0.7, 14.5, 0.3, 2.4, 84, array['fruit','source_usda_fdc','portion_realiste']),
  ('raspberries', null, 'Framboises', 125, 52, 1.2, 11.9, 0.7, 6.5, 86, array['fruit','source_usda_fdc','portion_realiste']),
  ('mango', null, 'Mangue', 150, 60, 0.8, 15.0, 0.4, 1.6, 83, array['fruit','source_usda_fdc','portion_realiste']),
  ('melon', null, 'Melon', 200, 34, 0.8, 8.2, 0.2, 0.9, 90, array['fruit','source_usda_fdc','portion_realiste']),
  ('apple_compote', null, 'Compote pomme', 100, 68, 0.2, 17.0, 0.1, 1.2, 80, array['fruit','dessert','source_usda_fdc','portion_realiste']),
  ('almonds', null, 'Amandes', 30, 579, 21.2, 21.6, 49.9, 12.5, 4, array['snack','oleagineux','source_usda_fdc','portion_realiste']),
  ('peanuts', null, 'Cacahuetes', 30, 567, 25.8, 16.1, 49.2, 8.5, 3, array['snack','oleagineux','source_usda_fdc','portion_realiste']),
  ('potato_chips', null, 'Chips', 45, 536, 7.0, 53.0, 35.0, 4.8, 2, array['snack','source_usda_fdc','portion_realiste']),
  ('popcorn_plain', null, 'Pop-corn nature', 30, 387, 12.9, 78.0, 4.5, 14.5, 3, array['snack','source_usda_fdc','portion_realiste']),
  ('orange_juice', null, 'Jus orange', 250, 45, 0.7, 10.4, 0.2, 0.2, 89, array['boisson','fruit','source_usda_fdc','portion_realiste']),
  ('cola', null, 'Cola', 330, 42, 0.0, 10.6, 0.0, 0.0, 90, array['boisson','sucre','source_usda_fdc','portion_realiste']),
  ('red_wine_150', null, 'Vin rouge 15cl', 150, 85, 0.1, 2.6, 0.0, 0.0, 86, array['boisson','alcool','source_usda_fdc','portion_realiste']),
  ('omelette_2_eggs', null, 'Omelette 2 oeufs', 140, 154, 11.0, 1.0, 11.5, 0.0, 74, array['plat','oeuf','petit-dej','portion_estimee','source_usda_fdc']),
  ('chicken_wrap', null, 'Wrap poulet', 280, 205, 13.0, 23.0, 7.0, 2.5, 58, array['plat','wrap','poulet','portion_estimee','source_usda_fdc']),
  ('chicken_caesar_salad', null, 'Salade cesar poulet', 330, 165, 13.0, 6.0, 10.0, 2.0, 70, array['plat','salade','poulet','portion_estimee','source_usda_fdc']),
  ('spaghetti_bolognese', null, 'Spaghetti bolognaise', 380, 155, 8.5, 20.0, 4.8, 2.2, 66, array['plat','pates','boeuf','portion_estimee','source_usda_fdc']),
  ('pasta_carbonara', null, 'Pates carbonara', 380, 210, 9.5, 21.0, 10.5, 1.5, 60, array['plat','pates','portion_estimee','source_usda_fdc']),
  ('chili_con_carne_rice', null, 'Chili con carne riz', 420, 145, 8.0, 20.0, 3.8, 4.0, 68, array['plat','riz','boeuf','portion_estimee','source_usda_fdc']),
  ('fried_rice_chicken', null, 'Riz saute poulet', 380, 165, 9.0, 22.0, 5.0, 2.0, 63, array['plat','riz','poulet','portion_estimee','source_usda_fdc']),
  ('quiche_lorraine', null, 'Quiche lorraine', 180, 300, 10.0, 21.0, 20.0, 1.2, 45, array['plat','tarte','portion_estimee','source_usda_fdc']),
  ('vegetable_soup', null, 'Soupe legumes', 300, 42, 1.5, 7.5, 1.0, 2.0, 90, array['plat','soupe','legumes','portion_estimee','source_usda_fdc']),
  ('kebab_sandwich', null, 'Kebab sandwich', 420, 245, 12.0, 24.0, 11.0, 2.0, 52, array['plat','sandwich','portion_estimee','source_usda_fdc']),
  ('french_tacos', null, 'Tacos francais', 500, 270, 12.0, 28.0, 12.0, 2.0, 48, array['plat','sandwich','portion_estimee','source_usda_fdc']),
  ('poke_bowl_salmon', null, 'Poke bowl saumon', 450, 145, 9.0, 18.0, 4.5, 3.0, 68, array['plat','riz','saumon','portion_estimee','source_usda_fdc'])
on conflict (key) do update set
  name = excluded.name,
  serving_grams = excluded.serving_grams,
  kcal_per_100g = excluded.kcal_per_100g,
  protein_per_100g = excluded.protein_per_100g,
  carbs_per_100g = excluded.carbs_per_100g,
  fat_per_100g = excluded.fat_per_100g,
  fiber_per_100g = excluded.fiber_per_100g,
  water_ml_per_100g = excluded.water_ml_per_100g,
  tags = excluded.tags,
  is_active = true,
  updated_at = now();

insert into public.sport_exercises
  (key, goal, equipment, activity_key, name_fr, name_en, mode, default_reps, default_seconds, default_sets, default_rest_seconds, distance_m, met_value, tags, sort_order)
values
  ('negative_pullup', 'strength', 'bodyweight', 'bodyweight_strength', 'Traction negative', 'Negative pull-up', 'reps', 5, null, 4, 90, null, 5.8, array['poids_du_corps','dos','pull','source_compendium_2024'], 224),
  ('assisted_pullup_band', 'strength', 'band', 'resistance_band_strength', 'Traction assistee elastique', 'Band-assisted pull-up', 'reps', 6, null, 4, 90, null, 5.6, array['elastique','dos','pull','source_compendium_2024'], 225),
  ('scap_pushup', 'strength', 'bodyweight', 'bodyweight_strength', 'Pompes scapulaires', 'Scapular push-up', 'reps', 12, null, 3, 45, null, 4.2, array['poids_du_corps','epaules','prehab','source_compendium_2024'], 226),
  ('side_lunge', 'strength', 'bodyweight', 'bodyweight_strength', 'Fente laterale', 'Side lunge', 'reps', 10, null, 3, 60, null, 5.2, array['poids_du_corps','jambes','lateral','source_compendium_2024'], 227),
  ('assisted_pistol_squat', 'strength', 'bodyweight', 'bodyweight_strength', 'Pistol squat assiste', 'Assisted pistol squat', 'reps', 6, null, 3, 90, null, 5.8, array['poids_du_corps','jambes','unilateral','source_compendium_2024'], 228),
  ('superman_hold', 'strength', 'bodyweight', 'plank_core', 'Superman tenu', 'Superman hold', 'time', null, 35, 3, 45, null, 3.8, array['poids_du_corps','dos','gainage','source_compendium_2024'], 315),
  ('pallof_press_band', 'strength', 'band', 'resistance_band_strength', 'Pallof press elastique', 'Band Pallof press', 'reps', 12, null, 3, 45, null, 4.2, array['elastique','core','anti_rotation','source_compendium_2024'], 415),
  ('band_good_morning', 'strength', 'band', 'resistance_band_strength', 'Good morning elastique', 'Band good morning', 'reps', 12, null, 3, 60, null, 4.8, array['elastique','chaine_posterieure','source_compendium_2024'], 416),
  ('dumbbell_incline_press', 'strength', 'dumbbell', 'strength', 'Developpe incline halteres', 'Incline dumbbell press', 'reps', 10, null, 3, 90, null, 5.8, array['halteres','pectoraux','push','source_compendium_2024'], 464),
  ('dumbbell_split_squat', 'strength', 'dumbbell', 'strength', 'Split squat halteres', 'Dumbbell split squat', 'reps', 8, null, 3, 90, null, 6.3, array['halteres','jambes','unilateral','source_compendium_2024'], 465),
  ('dumbbell_hammer_curl', 'strength', 'dumbbell', 'strength', 'Curl marteau halteres', 'Dumbbell hammer curl', 'reps', 12, null, 3, 60, null, 4.8, array['halteres','bras','biceps','source_compendium_2024'], 466),
  ('dumbbell_rear_delt_fly', 'strength', 'dumbbell', 'strength', 'Oiseau halteres', 'Dumbbell rear delt fly', 'reps', 12, null, 3, 60, null, 4.6, array['halteres','epaules','dos','source_compendium_2024'], 467),
  ('dumbbell_pullover', 'strength', 'dumbbell', 'strength', 'Pull-over haltere', 'Dumbbell pullover', 'reps', 10, null, 3, 75, null, 5.2, array['halteres','dos','pectoraux','source_compendium_2024'], 468),
  ('barbell_front_squat', 'strength', 'barbell', 'strength', 'Front squat barre', 'Barbell front squat', 'reps', 6, null, 4, 120, null, 6.5, array['barre','jambes','squat','source_compendium_2024'], 506),
  ('barbell_romanian_deadlift', 'strength', 'barbell', 'strength', 'Souleve de terre roumain barre', 'Barbell Romanian deadlift', 'reps', 8, null, 4, 120, null, 6.2, array['barre','ischios','chaine_posterieure','source_compendium_2024'], 507),
  ('machine_shoulder_press', 'strength', 'machine', 'strength', 'Developpe epaules machine', 'Machine shoulder press', 'reps', 10, null, 3, 75, null, 5.2, array['machine','epaules','push','source_compendium_2024'], 610),
  ('machine_hack_squat', 'strength', 'machine', 'strength', 'Hack squat machine', 'Hack squat machine', 'reps', 10, null, 3, 90, null, 5.8, array['machine','jambes','squat','source_compendium_2024'], 611),
  ('machine_hip_abduction', 'strength', 'machine', 'strength', 'Abducteurs machine', 'Machine hip abduction', 'reps', 12, null, 3, 60, null, 4.4, array['machine','fessiers','source_compendium_2024'], 612),
  ('machine_hip_adduction', 'strength', 'machine', 'strength', 'Adducteurs machine', 'Machine hip adduction', 'reps', 12, null, 3, 60, null, 4.4, array['machine','adducteurs','source_compendium_2024'], 613),
  ('cable_face_pull', 'strength', 'machine', 'strength', 'Face pull poulie', 'Cable face pull', 'reps', 15, null, 3, 45, null, 4.6, array['machine','epaules','prehab','source_compendium_2024'], 614),
  ('stair_climber', 'cardio', 'machine', 'hiit', 'Stair climber', 'Stair climber', 'time', null, 1200, 1, 0, null, 8.8, array['machine','cardio','jambes','source_compendium_2024'], 645),
  ('air_bike', 'cardio', 'machine', 'cycling', 'Air bike', 'Air bike', 'time', null, 60, 10, 60, null, 9.5, array['machine','cardio','hiit','source_compendium_2024'], 646),
  ('ski_erg', 'cardio', 'machine', 'rowing', 'SkiErg', 'SkiErg', 'time', null, 60, 8, 60, null, 8.5, array['machine','cardio','tirage','source_compendium_2024'], 647),
  ('incline_treadmill_walk', 'cardio', 'machine', 'walking', 'Marche inclinee tapis', 'Incline treadmill walk', 'time', null, 1200, 1, 0, null, 6.0, array['machine','marche','cardio','source_compendium_2024'], 648),
  ('boxing_double_end_bag', 'boxing', 'boxing', 'boxing', 'Double-end bag', 'Double-end bag', 'time', null, 120, 5, 45, null, 6.8, array['boxe','coordination','source_compendium_2024'], 810),
  ('boxing_bag_power_intervals', 'boxing', 'boxing', 'boxing', 'Intervalles puissance sac', 'Heavy bag power intervals', 'time', null, 45, 10, 45, null, 12.8, array['boxe','sac','puissance','source_compendium_2024'], 811),
  ('boxing_bag_technical_rounds', 'boxing', 'boxing', 'boxing', 'Rounds technique au sac', 'Heavy bag technical rounds', 'time', null, 180, 5, 60, null, 8.8, array['boxe','sac','technique','source_compendium_2024'], 812),
  ('boxing_conditioning_circuit', 'boxing', 'mixed', 'hiit', 'Circuit conditioning boxe', 'Boxing conditioning circuit', 'time', null, 40, 8, 20, null, 9.2, array['boxe','hiit','conditioning','source_compendium_2024'], 813)
on conflict (key) do update set
  goal = excluded.goal,
  equipment = excluded.equipment,
  activity_key = excluded.activity_key,
  name_fr = excluded.name_fr,
  name_en = excluded.name_en,
  mode = excluded.mode,
  default_reps = excluded.default_reps,
  default_seconds = excluded.default_seconds,
  default_sets = excluded.default_sets,
  default_rest_seconds = excluded.default_rest_seconds,
  distance_m = excluded.distance_m,
  met_value = excluded.met_value,
  tags = excluded.tags,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();
